nyaruka/goflow

- cmd/flowrunner/testdata/flows/two_questions.json
- excellent/legacy.go
- excellent/legacy_test.go
- flows/actions/save_flow_result.go
- flows/definition/legacy.go
- flows/definition/localization.go
- flows/engine/engine.go
- flows/events/save_flow_result.go
- flows/interfaces.go
- flows/results.go
- flows/routers/switch.go
- flows/runs/run.go
* Switches to arrays for localization dictionary
* Includes category_original if a localized category name is returned for events and flow results
> Localization updates

- flows/definition/legacy.go
Create update_contact action as appropriate, minor migration tweaks
> Migration Tweaks

- cmd/flowrunner/testdata/flows/all_actions_test.json
- cmd/flowrunner/testdata/flows/subflow_loop_test.json
- cmd/flowrunner/testdata/flows/subflow_test.json
- flows/definition/flow.go
- flows/definition/legacy.go
- flows/events/flow_exited.go
- flows/events/msg_received.go
- flows/interfaces.go
- flows/runs/run.go
- flows/waits/flow.go
- flows/waits/msg.go
* Add ExpiresAfterMinutes field to flows
* Ensure that's migrated on legacy flows
* Reset run expiration when input is received
> Run Expiration

- excellent/tests.go
> has_pattern should return a match object that exposes matching groups

- cmd/flowrunner/main.go
- cmd/flowrunner/runner_test.go
- cmd/flowrunner/testdata/flows/all_actions.json
- cmd/flowrunner/testdata/flows/all_actions_test.json
- cmd/flowrunner/testdata/flows/brochure_test.json
- cmd/flowrunner/testdata/flows/date_parse_test.json
- cmd/flowrunner/testdata/flows/default_result_test.json
- cmd/flowrunner/testdata/flows/subflow_other_test.json
- cmd/flowrunner/testdata/flows/subflow_test.json
- cmd/flowrunner/testdata/flows/two_questions_test.json
- cmd/flowrunner/testdata/flows/webhook_persists_test.json
- flows/actions/add_label.go
- flows/actions/add_to_group.go
- flows/actions/base.go
- flows/actions/remove_from_group.go
- flows/definition/legacy.go
- flows/engine/assets.go
- flows/events/add_label.go
- flows/events/envelope.go
- flows/events/msg_received.go
- flows/inputs/base.go
- flows/inputs/envelope.go
- flows/inputs/msg.go
- flows/interfaces.go
- flows/label.go
* Adds `msg_uuid` to `msg_received` events
* Adds `uuid` to Input
* If run has input, then `add_label` action generates `add_label` event with `input_uuid` and `label_uuids`
> Implement add_label and add labels as an asset type

- cmd/docgen/run.go
- cmd/flowrunner/main.go
- cmd/flowrunner/runner_test.go
- cmd/flowserver/config.go
- cmd/flowserver/main.go
- flows/engine/assets.go
- vendor/github.com/koding/multiconfig/env_test.go
- vendor/github.com/koding/multiconfig/example_test.go
- vendor/github.com/koding/multiconfig/file_test.go
- vendor/github.com/koding/multiconfig/flag.go
- vendor/github.com/koding/multiconfig/flag_test.go
- vendor/github.com/koding/multiconfig/multiconfig_test.go
- vendor/github.com/koding/multiconfig/tag_test.go
- vendor/github.com/koding/multiconfig/testdata/config.json
- vendor/github.com/koding/multiconfig/testdata/config.toml
- vendor/github.com/koding/multiconfig/testdata/config.yaml
- vendor/github.com/koding/multiconfig/testdata/demo.go
- vendor/github.com/koding/multiconfig/validator_test.go
Fixes #113 
There was an old version of multiconfig already in the project which I updated
> Asset cache settings from multiconfig

- cmd/flowrunner/testdata/flows/all_actions.json
- cmd/flowrunner/testdata/flows/all_actions_test.json
- flows/actions/add_label.go
- flows/actions/add_to_group.go
- flows/actions/add_urn.go
- flows/actions/base.go
- flows/actions/call_webhook.go
- flows/actions/remove_from_group.go
- flows/actions/reply.go
- flows/actions/save_contact_field.go
- flows/actions/save_flow_result.go
- flows/actions/send_email.go
- flows/actions/send_msg.go
- flows/actions/set_preferred_channel.go
- flows/actions/start_flow.go
- flows/actions/start_session.go
- flows/actions/update_contact.go
- flows/definition/legacy.go
- flows/definition/testdata/action_migrations.json
- flows/engine/session.go
- flows/interfaces.go
- flows/runs/run.go
Matches recently added functionality in RP
> Message attachments can contain expressions

- cmd/flowrunner/testdata/flows/dynamic_groups.json
- cmd/flowrunner/testdata/flows/dynamic_groups_test.json
- contactql/evaluator.go
- contactql/parser.go
- contactql/parser_test.go
- flows/contact.go
- flows/urns.go
and names in dynamic group queries
> Update contact searching to drop support for implicit conditions 

- cmd/flowrunner/main.go
- cmd/flowrunner/testdata/flows/all_actions_test.json
- cmd/flowrunner/testdata/flows/brochure_test.json
- cmd/flowrunner/testdata/flows/date_parse_test.json
- cmd/flowrunner/testdata/flows/default_result_test.json
- cmd/flowrunner/testdata/flows/subflow_other_test.json
- cmd/flowrunner/testdata/flows/subflow_test.json
- cmd/flowrunner/testdata/flows/two_questions_test.json
- cmd/flowrunner/testdata/flows/webhook_persists_test.json
- cmd/flowserver/server_test.go
- flows/channel.go
- flows/events/environment_changed.go
- flows/events/msg_received.go
- flows/inputs/envelope.go
- flows/inputs/msg.go
- flows/interfaces.go
(Requires #154 be merged first)
* Changes `msg_received` to take a `MsgInput` as payload
* Changes `environment_changed` to take an `Environment` as payload
* Changes `Input.channel` to serialize as a channel reference instead of just a UUID for consistency
> Event refactor part 3

- cmd/flowrunner/main.go
- cmd/flowrunner/testdata/flows/all_actions.json
- cmd/flowrunner/testdata/flows/two_questions.json
- cmd/flowserver/server_test.go
- flows/actions/call_webhook.go
- utils/http.go
- utils/http_test.go
- utils/validator.go
Addresses https://github.com/nyaruka/goflow/issues/143
> Validate HTTP methods on webhook actions 

- cmd/docgen/functions.go
- cmd/docgen/run.go
- cmd/flowrunner/testdata/flows/all_actions_test.json
- cmd/flowrunner/testdata/flows/brochure_test.json
- cmd/flowrunner/testdata/flows/dynamic_groups_test.json
- flows/contact.go
- flows/engine/testdata/trigger.json
> Contact groups and channel should be references instead of single UUIDs

- cmd/flowrunner/testdata/flows/all_actions_test.json
- cmd/flowrunner/testdata/flows/brochure_test.json
- cmd/flowrunner/testdata/flows/date_parse_test.json
- cmd/flowrunner/testdata/flows/default_result_test.json
- cmd/flowrunner/testdata/flows/subflow_other_test.json
- cmd/flowrunner/testdata/flows/subflow_test.json
- cmd/flowrunner/testdata/flows/triggered_test.json
- cmd/flowrunner/testdata/flows/two_questions_test.json
- flows/engine/session.go
- flows/events/run_result_changed.go
- flows/results.go
Fixes https://github.com/nyaruka/goflow/issues/184
> Rename result.input to .operand

- cmd/docgen/actions.go
- cmd/docgen/events.go
- cmd/docgen/functions.go
- cmd/docgen/main.go
- cmd/docgen/templates/docs.md
- cmd/docgen/templates/template.html
- docs/index.html
Updates based on discussion this morning. Would like to take a second pass at this future and have the examples be checked against a real context like how we do for actions, events etc.
Generated docs published at https://nyaruka.github.io/goflow/
> Update flow spec docs

- cmd/docgen/actions.go
- cmd/docgen/functions.go
- cmd/docgen/run.go
- docs/index.html
- flows/actions/add_contact_groups.go
- flows/actions/add_input_labels.go
- flows/actions/start_session.go
- flows/definition/node.go
- flows/interfaces.go
Fixes #193
Also consolidates the data used to start an example session
> Fix errors generated during docgen

- cmd/docgen/run.go
- cmd/flowrunner/testdata/flows/all_actions_test.json
- cmd/flowrunner/testdata/flows/brochure_test.json
- cmd/flowrunner/testdata/flows/date_parse_test.json
- cmd/flowrunner/testdata/flows/default_result_test.json
- cmd/flowrunner/testdata/flows/dynamic_groups.json
- cmd/flowrunner/testdata/flows/dynamic_groups_test.json
- cmd/flowrunner/testdata/flows/empty_test.json
- cmd/flowrunner/testdata/flows/node_loop_test.json
- cmd/flowrunner/testdata/flows/subflow_loop_test.json
- cmd/flowrunner/testdata/flows/subflow_other_test.json
- cmd/flowrunner/testdata/flows/subflow_test.json
- cmd/flowrunner/testdata/flows/triggered_test.json
- cmd/flowrunner/testdata/flows/two_questions_test.json
- cmd/flowrunner/testdata/flows/webhook_persists_test.json
- cmd/flowserver/server_test.go
- cmd/flowserver/static/start.json
- excellent/tests.go
- flows/contact.go
- flows/engine/session_test.go
- flows/engine/testdata/assets.json
- flows/engine/testdata/trigger.json
- flows/events/contact_field_changed.go
- flows/fields.go
- flows/group.go
- flows/urns.go
> Fields 2.0

- cmd/flowrunner/testdata/flows/date_parse.json
- cmd/flowrunner/testdata/flows/date_parse_test.json
- excellent/functions.go
- excellent/functions_test.go
- utils/dates.go
- utils/dates_test.go
> change date/time formats to new approved format

- excellent/functions.go
- excellent/functions_test.go
- legacy/expressions.go
- legacy/expressions_test.go
> remove int in expressions, map to round_down for legacy

- excellent/functions.go
- excellent/functions_test.go
fixes https://github.com/nyaruka/goflow/issues/204
> make round places argument optional, round to nearest, allow negative places

- excellent/evaluator_test.go
- excellent/functions.go
- excellent/functions_test.go
- excellent/visitor.go
Fixes: https://github.com/nyaruka/goflow/issues/95
> strict decimal comparison, add string_cmp

- cmd/flowrunner/testdata/flows/all_actions.json
- cmd/flowrunner/testdata/flows/all_actions_test.json
- cmd/flowrunner/testdata/flows/date_parse.json
- cmd/flowrunner/testdata/flows/date_parse_test.json
- cmd/flowrunner/testdata/flows/default_result.json
- cmd/flowrunner/testdata/flows/default_result_test.json
- cmd/flowrunner/testdata/flows/dynamic_groups.json
- cmd/flowrunner/testdata/flows/dynamic_groups_test.json
- cmd/flowrunner/testdata/flows/empty_test.json
- flows/actions/set_contact_field.go
- flows/events/contact_field_changed.go
- flows/fields.go
- flows/references.go
- legacy/testdata/migrations/actions.json
Fixes https://github.com/nyaruka/goflow/issues/208
> change label  to name on contactfield

- flows/engine/session_test.go
- flows/engine/testdata/assets.json
- flows/results.go
> Looking up non-existent run result is an error

- docs/docs.md
- docs/index.html
- excellent/functions/functions.go
- legacy/expressions.go
- legacy/expressions_test.go
> word_slice should be zero-based

- cmd/docgen/docs.go
- docs/docs.md
- docs/index.html
- excellent/functions/functions.go
- excellent/functions/functions_test.go
- excellent/functions/wrappers.go
- flows/routers/random.go
- flows/routers/random_once.go
- legacy/expressions.go
- legacy/expressions_test.go
- utils/rand.go
- utils/uuid.go
* `rand` split into `rand` and `rand_between` (same as legacy function)
* Results of RAND()/RAND_BETWEEN()/random routers now mockable for tests and docs
* Added few more function wrappers, e.g. `NoArgFunction`
Fixes #235
> A Random PR

- docs/docs.md
- docs/index.html
- excellent/functions/functions.go
- flows/contact.go
- flows/routers/tests/tests.go
- test/session.go
- utils/dates.go
It should default to the session environment timezone
Fixes #250
> Fix contact timezone defaulting to UTC

- cmd/exptester/main.go
> Expression tester cmd should use standard test session

- cmd/flowrunner/testdata/flows/all_actions.json
- cmd/flowrunner/testdata/flows/default_result.json
- cmd/flowrunner/testdata/flows/no_contact.json
- flows/definition/flow.go
- flows/definition/flow_test.go
- flows/definition/testdata/flow_validation.json
> Validate that flow node UUIDs and actions UUIDs are unique

- docs/docs.md
- docs/index.html
- excellent/functions/functions.go
- excellent/types/array.go
- excellent/types/base.go
- excellent/types/conversions_test.go
- excellent/types/map.go
- flows/routers/tests/tests.go
Introduces the concept of _empty_ to determine what `default()` and `has_value()` should return
> Empty values

- cmd/flowserver/server.go
- legacy/definition.go
- legacy/definition_test.go
- legacy/testdata/migrations/flows.json
> Migration of stickies and make migration of all UI optional

- Gopkg.lock
- Gopkg.toml
- cmd/flowrunner/main.go
- cmd/flowrunner/runner_test.go
- vendor/github.com/sergi/go-diff/AUTHORS
- vendor/github.com/sergi/go-diff/CONTRIBUTORS
- vendor/github.com/sergi/go-diff/LICENSE
- vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
- vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
So that we catch *all* differences in the output, e.g.
> Use real diffing for flow tests 

- cmd/flowrunner/testdata/flows/all_actions.json
- cmd/flowrunner/testdata/flows/all_actions_test.json
- docs/docs.md
- docs/index.html
- flows/actions/remove_contact_groups.go
- flows/contact.go
- flows/group.go
- flows/group_test.go
- legacy/definition.go
- legacy/testdata/actions.json
> Remove all groups

- cmd/flowserver/config.go
- cmd/flowserver/server_test.go
- flows/engine/config.go
- flows/interfaces.go
- flows/webhook.go
- utils/http.go
> Mockable webhooks

- flows/contact.go
- flows/contact_test.go
- flows/events/contact_field_changed.go
- flows/fields.go
- flows/group.go
- test/environment.go
> Dynamic groups on created_on and language

- cmd/flowserver/middleware.go
- cmd/flowserver/server.go
- excellent/types/base.go
- excellent/types/boolean.go
- excellent/types/text.go
and protect against nil pointer panics in type conversion functions
> 💣 Panic recovery middleware

- legacy/definition.go
- legacy/ui.go
> Migrate ruleset_types to editor types in _ui

- excellent/evaluator_test.go
- excellent/input.go
- excellent/input_test.go
- excellent/scanner.go
- excellent/scanner_test.go
- legacy/expressions/migrate_test.go
* Fixes not parsing `@contact...` correctly by only including trailing periods when the following char is a valid name char
* Fixes `@(")")` so that the `)` in the string literal doesn't close the expression
> 📠 Scanner fixes

- cmd/flowserver/handlers.go
- legacy/definition.go
- legacy/definition_test.go
- legacy/testdata/rulesets.json
... that fixes an ordering bug and adds option to not collapse exits
> Small refactor of how we migrate rules to cases/exits 

- cmd/flowrunner/testdata/default.json
- cmd/flowrunner/testdata/flows/all_actions.json
- cmd/flowrunner/testdata/flows/all_actions_test.json
- cmd/flowrunner/testdata/flows/router_tests.json
- cmd/flowrunner/testdata/flows/router_tests_test.json
- flows/actions/base.go
- flows/field.go
- test/session.go
Fixes https://sentry.io/nyaruka/rapidpro-goflow/issues/673879092/ amongst other problems
> 🗺️ Location parsing fixes

- flows/contact.go
- flows/contact_test.go
- flows/engine/session_test.go
cuz we need to build full contacts
> add full constructor for contact

- docs/expressions.html
- docs/md/expressions.md
- excellent/functions/functions.go
- excellent/functions/wrappers.go
- excellent/types/array.go
- excellent/types/array_test.go
- excellent/types/base.go
- excellent/types/base_test.go
- excellent/types/map.go
- excellent/types/map_test.go
- flows/contact.go
- flows/engine/session_test.go
So we don't end up putting quotes around booleans and numbers etc
> Tweak how we do conversion to XText on expression values

- flows/interfaces.go
- legacy/definition.go
- legacy/testdata/flows.json
- legacy/testdata/rulesets.json
- legacy/ui.go
* Add migration type for Airtime
* Make non-router nodes declare a type
* Nest operand for various ui configs for consistency
> ⛓ More migrations

- cmd/flowrunner/main.go
- flows/contact.go
- flows/engine/session.go
- flows/events/contact_changed.go
- flows/runs/summary.go
- flows/triggers/base.go
When resuming from a JSON session blob, it's possible these no longer exist. Addresses #383.
> 🤷 Allow contacts to be loaded in a mode that ignores missing groups or fields

- cmd/docgen/docs.go
- cmd/docgen/main.go
- cmd/docgen/renderers.go
- docs/functions.json
Addresses #372 
```json
{
"signature": "boolean(value)",
"summary": "Tries to convert `value` to a boolean.",
"detail": "An error is returned if the value can't be converted.",
"examples": [
{
"template": "@(boolean(array(1, 2)))",
"output": "true"
},
{
"template": "@(boolean(\"FALSE\"))",
"output": "false"
},
{
"template": "@(boolean(1 / 0))",
"output": "ERROR"
}
]
}
```
> 📚 Generate a JSON listing of functions

- docs/flows.html
- docs/functions.json
- docs/md/flows.md
- flows/actions/add_contact_urn.go
- flows/actions/set_contact_field.go
- flows/actions/set_contact_language.go
- flows/actions/set_contact_name.go
- flows/actions/set_contact_timezone.go
- flows/contact.go
- flows/contact_test.go
- flows/field.go
- flows/field_test.go
* Only generate a `contact_field_changed` event if a value has actually changed
* Only trigger dynamic group re-eval if value has changed
> 🔖 Field tweaks

- cmd/flowrunner/runner_test.go
- cmd/flowrunner/testdata/flows/dynamic_groups.json
- cmd/flowrunner/testdata/flows/dynamic_groups_correction.json
- cmd/flowrunner/testdata/flows/dynamic_groups_correction_test.json
- cmd/flowrunner/testdata/flows/dynamic_groups_test.json
- flows/resumes/base.go
- flows/triggers/base.go
> 🗜️ Re-evaluate and correct contact groups at the start of a session

- flows/engine/flow_stack.go
- flows/engine/session.go
- flows/interfaces.go
- flows/triggers/msg.go
- flows/waits/base.go
- flows/waits/msg.go
- test/runner_test.go
- test/testdata/flows/initial_wait.json
- test/testdata/flows/initial_wait_test.json
And have the msg wait skip itself if it's the first thing after a msg trigger. Fixes #59.
> ⏭️ Allow waits to skip themselves

- docs/flows.html
- docs/md/flows.md
- docs/md/sessions.md
- docs/sessions.html
- flows/actions/start_flow.go
- flows/engine/session.go
- flows/events/flow_triggered.go
- flows/interfaces.go
- flows/triggers/base.go
- legacy/definition.go
- legacy/testdata/actions.json
- legacy/testdata/rulesets.json
- test/runner_test.go
- test/testdata/flows/all_actions_test.json
- test/testdata/flows/start_flow_terminal.json
- test/testdata/flows/start_flow_terminal_test.json
- test/testdata/flows/subflow_loop_test.json
- test/testdata/flows/subflow_other_test.json
- test/testdata/flows/subflow_test.json
To replicate behavior of start flow actions (i.e. not rulesets) in legacy flows. Fixes #139.
> 🧟 Add new terminal option to start_flow actions

- README.md
- cmd/flowrunner/main.go
- cmd/flowrunner/main_test.go
- flows/resumes/base.go
- flows/resumes/msg.go
- flows/resumes/run_expiration.go
- flows/resumes/wait_timeout.go
- flows/triggers/base.go
- flows/triggers/campaign.go
- flows/triggers/channel.go
- flows/triggers/flow_action.go
- flows/triggers/manual.go
- flows/triggers/msg.go
> 🏃 Generate test cases from flowrunner (again)

- flows/definition/flow_test.go
- flows/waits/msg.go
- flows/waits/msg_test.go
- legacy/definition.go
- legacy/testdata/rulesets.json
> 📸 Media wait hints

- docs/md/sessions.md
- docs/sessions.html
- flows/events/base_test.go
- flows/events/contact_field_changed.go
This is valid and indicates the field value has been cleared
> 🔥 Fix not being to read contact_field_changed events where value is null

- legacy/expressions/migrate.go
- legacy/expressions/migrate_test.go
> 🥛 Migrate @("") to empty string

- cmd/flowrunner/main.go
- cmd/flowserver/server_test.go
- flows/actions/base_test.go
- flows/inputs/msg_test.go
- flows/msg.go
- flows/msg_test.go
- flows/waits/msg_test.go
> 💬 Add external ID to MsgIn

- docs/expressions.html
- docs/functions.json
- docs/md/expressions.md
- excellent/functions/functions.go
- excellent/functions/functions_test.go
- flows/contact.go
- flows/contact_test.go
- flows/engine/session_test.go
- flows/urn.go
- flows/urn_test.go
- legacy/expressions/context.go
- legacy/expressions/migrate_test.go
- legacy/testdata/actions.json
- legacy/testdata/rulesets.json
- test/testdata/flows/router_tests.json
- test/testdata/flows/two_questions.json
> ⚡ Make @contact.urn a way to access single URNs by scheme

- cmd/flowrunner/main.go
- docs/flows.html
- docs/md/flows.md
- flows/actions/base_test.go
- flows/connection.go
- flows/connection_test.go
- flows/engine/session_test.go
- flows/triggers/base.go
- flows/triggers/base_test.go
- flows/triggers/campaign.go
- flows/triggers/channel.go
- flows/triggers/flow_action.go
- flows/triggers/manual.go
- flows/triggers/msg.go
- flows/waits/msg_test.go
- mobile/bindings.go
* Removes triggerOn from trigger constructors
* Adds two specialized constructors for IVR
Addresses #477
> 🔫 Simpler trigger constructors

- legacy/expressions/functions.go
- legacy/expressions/functions_test.go
Old engine returns Sun(1)...Sat(6), new engine returns Sun(0).. Sat(6)
Fixes #504
> 📅 Fix migration of weekday() to add 1

- flows/events/webhook_called.go
- flows/webhook.go
- flows/webhook_test.go
- test/http.go
- test/testdata/flows/resthook.json
- test/testdata/flows/resthook_test.json
> 🔍 Try to detect webhook response content type if header missing

- docs/expressions.html
- docs/md/expressions.md
- excellent/types/time.go
- flows/routers/tests/tests.go
- utils/dates.go
- utils/dates_test.go
- utils/text.go
- utils/text_test.go
- utils/timeofday.go
- utils/timeofday_test.go
* Accept hh, e.g. "12" or "2 PM"
* Accept hhmm, e.g. "1400"
* Accept "24:00" as midnight
> 🕰️ More flexible time parsing

- contactql/parser.go
- docs/expressions.html
- docs/functions.json
- docs/md/expressions.md
- excellent/functions/functions.go
- excellent/functions/functions_test.go
- excellent/functions/wrappers.go
- excellent/types/date.go
- excellent/types/date_test.go
- excellent/types/datetime.go
- excellent/types/datetime_test.go
- excellent/types/time_test.go
- legacy/expressions/context.go
- legacy/expressions/functions_test.go
- legacy/expressions/migrate_test.go
- utils/date.go
- utils/date_test.go
- utils/dates.go
- utils/dates_test.go
- utils/timeofday.go
> 📅 Timeless dates

- excellent/visitor.go
- flows/runs/context_test.go
fixes https://sentry.io/organizations/nyaruka/issues/899923889/?project=1281372
> 🔥 fix resolving @parent or @child when they are nil

- docs/expressions.html
- docs/functions.json
- docs/md/expressions.md
- excellent/functions/functions.go
- excellent/functions/functions_test.go
- legacy/expressions/functions.go
- legacy/expressions/functions_test.go
- legacy/expressions/migrate_test.go
More tweaks in the quest for perfect compatibility with legacy expressions..
* `datetime_from_parts` &rarr; `date_from_parts` (`DATE` migrates to this )
* added `date` (`DATEVALUE` migrates to this )
> 📆 Date function tweaks

- legacy/expressions/migrate.go
- legacy/expressions/migrate_test.go
- legacy/expressions/visitor.go
Wrap results of date arithmetic in format_date to match legacy behavior of returning date from date-only arithmetic, and stringifying dates in org format
Addresses #532
> 🚒 Yet another legacy date arithmetic fix

- legacy/expressions/migrate.go
- legacy/expressions/migrate_test.go
- legacy/expressions/visitor.go
So cool we found the last migration of legacy date arithmetic bug (#539) 😬
> 🚁 Fix migration of datevalue() + time

- legacy/expressions/migrate_test.go
- legacy/expressions/visitor.go
I was secretly hoping nobody really does this because the migrated expression is a bit nuts.. but apparently it is a thing people do, or at least our existing docs say it's a thing you can do.
> 🤯 Migrate datetime+time to a minutes addition expression

- legacy/expressions/migrate_test.go
- legacy/expressions/visitor.go
One last fix for migration of legacy date arithmetic expressions before I go start selling 🍢
Fixes https://app.intercom.io/a/apps/l6e7tr01/inbox/inbox/155936/conversations/20906198371
> 🔥 Fix migration of datetime + time in legacy expressions

- cmd/flowrunner/main.go
- flows/actions/set_contact_field.go
- flows/actions/testdata/call_webhook.json
- flows/definition/assets_test.go
- flows/definition/dependencies.go
- flows/definition/flow.go
- flows/definition/flow_test.go
- flows/definition/testdata/assets_with_only_flow.json
- flows/engine/assets.go
- flows/engine/session.go
- flows/interfaces.go
- flows/triggers/base.go
- test/session.go
> 🔏 Add validation at session assets level which returns missing assets

- flows/definition/flow.go
Fixes https://sentry.io/organizations/nyaruka/issues/946826255/?project=1285856&referrer=alert_email&statsPeriod=14d
> 🔥 Don't try to validate a subflow which is missing

- flows/routers/switch.go
- flows/routers/testdata/switch.json
Bug introduced in categories vs exits refactor
> 🔥 Switch router should use category from first matching rule

- utils/location.go
- utils/location_test.go
Addresses https://github.com/nyaruka/goflow/issues/592
> Normalize value looked up to match locations

- legacy/definition.go
- legacy/testdata/rulesets.json
> 🔧 Ruleset of type contact_field that splits on @contact.group becomes expression split

- cmd/flowrunner/main.go
- flows/engine/session.go
- flows/interfaces.go
- flows/routers/base.go
- flows/routers/random.go
- flows/routers/switch.go
Instead of having the router try to figure out if there is a timeout happening
> 🔥 Explicitly route as timeout when we receive a timeout resume

- flows/actions/call_webhook.go
- flows/actions/testdata/call_webhook.json
- legacy/definition.go
And validate that header names are valid during validation
> 🌐 Ignore empty webhook headers during flow migration

- docs/context.html
- docs/functions.json
- docs/md/context.md
- excellent/functions/builtin.go
- excellent/functions/builtin_test.go
- flows/engine/session_test.go
- flows/routers/cases/tests.go
- flows/routers/cases/tests_test.go
> ❌ is_error as a regular function, has_error as a router case test

- contactql/evaluator.go
- contactql/parser_test.go
Closes: #625
Add support for comparing text using `!=` operator
> 💇🏿‍♀️ Support != operator

- docs/context.html
- docs/md/context.md
- flows/engine/session_test.go
- flows/interfaces.go
- flows/runs/run_test.go
- flows/runs/summary.go
- legacy/definition.go
- legacy/expressions/context.go
- legacy/expressions/functions_test.go
- legacy/expressions/migrate_test.go
- legacy/testdata/rulesets.json
- test/testdata/runner/subflow.json
- test/testdata/runner/subflow_other.json
- test/testdata/runner/triggered.json
> 👪 @child and @parent should mirror root of context, not @run

- legacy/definition.go
- legacy/testdata/rulesets.json
- legacy/ui.go
> 🛫 Extract delta param from legacy date_ rules and save in UI

- excellent/functions/builtin_test.go
- flows/actions/base_test.go
- flows/actions/set_run_result.go
- flows/actions/testdata/set_run_result.json
- go.mod
- go.sum
> allow empty results, fix empty category calculations

- flows/routers/cases/tests.go
- flows/routers/cases/tests_test.go
- flows/routers/switch.go
- flows/routers/testdata/switch.json
> 🧪 Validate that switch case tests are registered XTESTs

- docs/context.html
- docs/md/context.md
- flows/contact.go
- flows/engine/session_test.go
- flows/field.go
- flows/field_test.go
- flows/interfaces.go
- flows/results.go
- flows/runs/run.go
- flows/runs/run_test.go
- flows/runs/summary.go
> 🎁 More context defaults

- flows/engine/session.go
- flows/routers/base.go
- flows/routers/base_test.go
- flows/routers/testdata/random.json
- flows/routers/testdata/switch.json
> 🔥 Router failing to pick category should be fatal error event - not hard error

- flows/actions/base.go
- flows/engine/session_test.go
- flows/expressions.go
- flows/interfaces.go
- flows/runs/run.go
- flows/webhook.go
- flows/webhook_test.go
- test/http.go
- test/utils.go
> 🎣 Add @webhook as shortcut to .extra of last webhook result

- assets/references.go
- assets/references_test.go
- flows/actions/testdata/send_msg.json
- flows/definition/dependencies.go
- flows/definition/flow.go
- flows/definition/flow_test.go
- flows/definition/testdata/flow_with_missing_asset.json
- flows/template.go
- flows/template_test.go
Wasn't being included in the dependencies json as they are included by type.
> properly return template dependencies for flows

- flows/definition/flow.go
Forgot when I made #677 that we sometimes need to inspect a flow (get it's dependencies) without actually checking they exist
> 🕵️‍♂️ (Re)allow inspecting without session assets

- flows/actions/base.go
- flows/actions/base_test.go
- flows/actions/call_resthook.go
- flows/actions/call_webhook.go
- flows/actions/set_run_result.go
- flows/actions/testdata/call_resthook.json
- flows/actions/testdata/call_webhook.json
- flows/actions/testdata/set_run_result.json
- flows/definition/flow.go
- flows/definition/flow_test.go
- flows/definition/node.go
- flows/inspect.go
- flows/inspect_test.go
- flows/routers/base.go
- flows/routers/switch.go
- flows/routers/testdata/random.json
- flows/routers/testdata/switch.json
> 🛒 Include node UUIDs in result infos returned from flow inspection

- flows/routers/cases/tests.go
- flows/routers/switch.go
- flows/routers/testdata/switch.json
- legacy/definition.go
- legacy/testdata/rulesets.json
- legacy/testdata/tests.json
Used only in dependency inspection
> 🏷️ has_group can take optional second parameter for group name

- flows/definition/flow_test.go
- flows/definition/generic.go
For example arguments passed to `has_group` tests
> 👯 Remapping UUIDs during cloning must include UUIDs which are values in arrays

- flows/actions/base.go
- flows/actions/send_broadcast.go
- flows/actions/start_session.go
- flows/actions/testdata/send_broadcast.json
- flows/actions/testdata/start_session.json
> 📣 Accept full URNs for broadcasty actions and NOOP if no recipients

- excellent/functions/builtin_test.go
- excellent/types/json.go
- excellent/types/json_test.go
- flows/actions/call_resthook.go
- flows/webhook.go
- utils/json.go
- utils/json_test.go
* Switch to using `json.Valid` to validate JSON
* Validate JSON being parsed to X values
> 💎 Valid JSON

- excellent/functions/builtin.go
- excellent/functions/builtin_test.go
Fixes https://sentry.io/organizations/nyaruka/issues/1083984167/?project=227973&referrer=alert_email
> 🧨 Fix format excellent function when passed a nil

- contactql/parser.go
- contactql/visitor.go
- go.sum
Just adding some getters so that mailroom can get at what it needs.
> tweak to goflow interfaces to allow introspection into contactql

- flows/actions/base_test.go
- flows/actions/send_email.go
- flows/actions/testdata/_assets.json
- flows/actions/testdata/send_broadcast.json
- flows/actions/testdata/send_email.json
And adds a way to test localization in action tests
> 📧 Update send_email action to allow localization of subject and body

- flows/triggers/flow_action.go
Currently only have a manual IVR trigger constructor, so needed a version that takes a parent summary.
> add ivr flow trigger constructor

- flows/triggers/flow_action.go
> rename voice trigger to be more consistent

- excellent/types/object.go
- excellent/types/object_test.go
- flows/interfaces.go
- flows/runs/legacy.go
- flows/triggers/base.go
- flows/triggers/base_test.go
- flows/triggers/channel.go
- flows/triggers/manual.go
And always non-null in expressions
> 🔩 Change trigger.params to be an XObject 

- excellent/tools/context_refs.go
- excellent/tools/context_refs_test.go
> 🔥 Fix parsing context references like foo.0

- cmd/docgen/renderers.go
- cmd/docgen/templates/styles.css
- docs/assets.html
- docs/context.html
- docs/expressions.html
- docs/flows.html
- docs/md/assets.md
- docs/md/context.md
- docs/md/expressions.md
- docs/md/flows.md
- docs/md/routing.md
- docs/md/sessions.md
- docs/routing.html
- docs/sessions.html
- docs/styles.css
Make documented item titles into actual links so it's easier to get the link of a particular item in the docs.
Addresses #753
> 📚 Easier linking to specific items in docs

- flows/engine/session.go
- test/testdata/runner/enter_flow_loop.test.json
- test/testdata/runner/enter_flow_terminal.test.json
> 🔋 A terminal enter_flow action should leave existing runs as completed

- docs/md/sessions.md
- docs/sessions.html
- flows/actions/add_contact_groups.go
- flows/actions/add_input_labels.go
- flows/actions/base.go
- flows/actions/remove_contact_groups.go
- flows/actions/send_broadcast.go
- flows/actions/start_session.go
- flows/actions/testdata/send_broadcast.json
- flows/actions/testdata/start_session.json
- flows/events/base_test.go
- flows/events/broadcast_created.go
- flows/events/session_triggered.go
- flows/inspect/templates_test.go
Diff is a bit bigger than you'd expect cuz I wanted to bake this functionality into the base class of `start_session` and `send_broadcast`.
> 🔎 Add contact_query field to start_session actions

- cmd/flowrunner/main.go
- cmd/transferairtime/main.go
- flows/actions/call_classifier.go
- flows/actions/call_resthook.go
- flows/actions/call_webhook.go
- flows/actions/transfer_airtime.go
- flows/engine/engine.go
- flows/engine/services.go
- flows/services.go
- services/webhooks/service.go
- services/webhooks/service_test.go
- test/engine.go
All service factory methods should return an error if service can't be returned
> 🏭 Service factory errors 

- docs/flows.html
- docs/md/flows.md
- flows/actions/play_audio.go
- flows/actions/say_msg.go
- flows/actions/send_msg.go
- flows/actions/testdata/send_msg.json
- flows/events/base_test.go
- flows/msg.go
- utils/validator.go
- utils/validator_test.go
Can be tweaked depending on conclusions of https://github.com/rapidpro/rapidpro/issues/1103
> 📖 Add topic to send_msg actions

- cmd/docgen/completion.go
- cmd/docgen/completion/completion.go
- cmd/docgen/main_test.go
- cmd/docgen/renderers.go
- docs/completion.json
- docs/completion.txt
- docs/context.html
- docs/md/context.md
- flows/runs/run.go
Last step of adding globals is making them appear in auto-completion
> @ Add @globals to completion

- flows/definition/legacy/definition.go
- flows/definition/legacy/definition_test.go
- flows/definition/legacy/expressions/context.go
- flows/definition/legacy/expressions/migrate.go
- flows/definition/legacy/expressions/visitor.go
- flows/definition/legacy/testdata/rulesets.json
- flows/definition/legacy/testdata/tests.json
> 🐿️ Fix migration of eq/after/before ruleset tests

- flows/actions/call_webhook.go
- flows/actions/testdata/call_webhook.json
- flows/definition/flow_test.go
- flows/definition/testdata/broken_flows/invalid_action_by_method.json
> 🤷 Allow request bodies with GET methods

- flows/actions/base_test.go
- flows/actions/testdata/add_contact_groups.json
- flows/actions/testdata/add_contact_urn.json
- flows/actions/testdata/add_input_labels.json
- flows/actions/testdata/call_classifier.json
- flows/actions/testdata/call_resthook.json
- flows/actions/testdata/call_webhook.json
- flows/actions/testdata/enter_flow.json
- flows/actions/testdata/play_audio.json
- flows/actions/testdata/remove_contact_groups.json
- flows/actions/testdata/say_msg.json
- flows/actions/testdata/send_broadcast.json
- flows/actions/testdata/send_email.json
- flows/actions/testdata/send_msg.json
- flows/actions/testdata/set_contact_channel.json
- flows/actions/testdata/set_contact_field.json
- flows/actions/testdata/set_contact_language.json
- flows/actions/testdata/set_contact_name.json
- flows/actions/testdata/set_contact_timezone.json
- flows/actions/testdata/set_run_result.json
- flows/actions/testdata/start_session.json
- flows/actions/testdata/transfer_airtime.json
- flows/routers/base_test.go
- flows/routers/testdata/random.json
- flows/routers/testdata/switch.json
- test/runner_test.go
- test/utils.go
So tired of updating these manually
> 💉 Snapshot tests for actions and routers

- flows/inspect/issues/base.go
- flows/inspect/issues/base_test.go
- flows/inspect/issues/missing_dependency.go
- flows/inspect/issues/testdata/_assets.json
- flows/inspect/issues/testdata/missing_dependency.json
- go.mod
> 🤷 Allow flow inspection without assets

- flows/contact.go
- flows/contact_test.go
- flows/group.go
- flows/group_test.go
> 💥 Handle missing groups on contact creation

- flows/contact.go
- flows/contact_test.go
- flows/group.go
- flows/testdata/dynamic_groups.assets.json
- flows/testdata/dynamic_groups.json
- test/assets.go
> 🐌 Remove contacts from broken groups

- excellent/base.go
- excellent/base_test.go
- flows/inspect/issues/invalid_regex.go
- flows/inspect/issues/testdata/invalid_regex.json
- flows/inspect/templates.go
Contains #864 which should be merged first
> 👮‍♀️ Issue for invalid regexes

- cmd/docgen/main_test.go
- docs/expressions.html
- docs/functions.json
- docs/md/expressions.md
- excellent/functions/builtin.go
- excellent/functions/builtin_test.go
- excellent/functions/wrappers.go
Adds https://github.com/rapidpro/rapidpro/issues/1162
> 💇 Text trimming functions

- cmd/flowrunner/main.go
- flows/actions/base_test.go
- flows/engine/engine_test.go
- flows/events/base_test.go
- flows/services_test.go
- services/airtime/dtone/client.go
- services/classification/bothub/client.go
- services/classification/luis/client.go
- services/classification/luis/client_test.go
- services/classification/luis/service.go
- services/classification/luis/service_test.go
- services/classification/wit/client.go
- services/webhooks/service.go
- test/engine.go
- test/runner_test.go
- utils/httpx/access.go
- utils/httpx/access_test.go
- utils/httpx/http.go
- utils/httpx/http_test.go
- utils/httpx/mock_test.go
- utils/httpx/retries_test.go
Includes webhooks and LUIS classifiers
> 🛑 Allow HTTP services to be configured with a list of disallowed hosts

- contactql/parser_test.go
- contactql/visitor.go
Addresses https://github.com/rapidpro/rapidpro/issues/1170
> Allow queries on URNs to check if they are set or not

- i18n/flows.go
- i18n/po.go
- i18n/po_test.go
- i18n/testdata/translation_mismatches.noargs.es.po
- i18n/testdata/two_questions.en.po
- i18n/testdata/two_questions.fr.po
- i18n/testdata/two_questions.noargs.fr.po
Next step would be importing PO file translations into actual flows
> ⚙️ Add generic read support for PO files

- cmd/docgen/main_test.go
- docs/expressions.html
- docs/functions.json
- docs/md/expressions.md
- excellent/functions/builtin.go
- excellent/functions/builtin_test.go
Fixes https://github.com/nyaruka/goflow/issues/893
> Add html_decode excellent func

- flows/definition/flow_test.go
- flows/interfaces.go
- flows/routers/base.go
- flows/routers/category.go
- flows/routers/random.go
- flows/routers/switch.go
Just want to be able to look at categories on a `flows.Router`
> Make categories inspectable - i.e. add interface in flows package

- README.md
- cmd/flowrunner/main.go
- cmd/transferairtime/main.go
- flows/actions/base.go
- flows/actions/base_test.go
- flows/actions/open_ticket.go
- flows/actions/send_broadcast.go
- flows/actions/start_session.go
- flows/actions/testdata/open_ticket.json
- flows/actions/testdata/send_broadcast.json
- flows/actions/testdata/start_session.json
- flows/contact_test.go
- flows/engine/engine.go
- flows/engine/session.go
- flows/interfaces.go
- flows/resumes/base_test.go
- flows/routers/base_test.go
- flows/routers/waits/msg_test.go
- flows/runs/environment_test.go
- flows/triggers/base.go
- flows/triggers/base_test.go
- flows/triggers/campaign.go
- flows/triggers/channel.go
- flows/triggers/flow_action.go
- flows/triggers/manual.go
- flows/triggers/msg.go
- mobile/bindings.go
- test/session.go
> 🦶 Builtin footgun prevention

- cmd/flowrunner/main.go
- flows/contact.go
- flows/field.go
- flows/field_test.go
- test/testdata/runner/field_clear.json
- test/testdata/runner/field_clear.test.json
Fixes https://github.com/rapidpro/rapidpro/issues/1239. Problem here is clearing a field removes it from the field->value map so if you try to reference it again in the same sprint.. boom.
The need for a set action prior is just to make sure there's a value to be cleared otherwise this clear-field action is a noop.
> 🐝 Fix clearing of fields

- docs/en_US/md/sessions.md
- docs/en_US/sessions.html
- docs/pt_BR/md/sessions.md
- docs/pt_BR/sessions.html
- flows/actions/testdata/call_classifier.json
- flows/events/base_test.go
- flows/events/service_called.go
- services/classification/wit/client.go
- services/classification/wit/client_test.go
- services/classification/wit/service.go
- services/classification/wit/service_test.go
- services/classification/wit/testdata/TestMessage_message_request.snap
> 🤖 Use latest wit.ai API version

- contactql/evaluator.go
- contactql/evaluator_test.go
- flows/contact_test.go
Hopefully addresses https://github.com/nyaruka/mailroom/issues/386
> 🔍 Engine evaluator for contactsql should support != x for numbers and datetimes

- flows/actions/base.go
- flows/definition/flow.go
- flows/definition/flow_test.go
- flows/definition/node.go
- flows/definition/testdata/broken_flows/invalid_action_by_flow_type.json
- flows/definition/testdata/broken_flows/invalid_flow_type.json
- flows/definition/testdata/broken_flows/invalid_wait_by_flow_type.json
- flows/flows.go
- flows/flows_test.go
- flows/interfaces.go
- flows/routers/base.go
- flows/routers/random.go
- flows/routers/switch.go
- flows/routers/waits/msg.go
Currently defined as a messaging flow without waits
> 🛏️ Add new flow type for passive messaging flows

- docs/es/completion.json
- docs/es/completion.txt
- docs/pt-br/completion.json
- docs/pt-br/completion.txt
- locale/en_US/flows.po
- locale/es/flows.po
- locale/fr/flows.po
- locale/pt_BR/flows.po
- locale/ru/flows.po
- utils/i18n/library_test.go
- utils/i18n/po.go
- utils/i18n/po_test.go
- utils/i18n/testdata/locale/en/simple.po
- utils/i18n/testdata/locale/es/simple.po
> Don't use fuzzy entries in po files

- flows/routers/waits/dial.go
- flows/routers/waits/dial_test.go
cuz mailroom needs it to actually do the dial!
> Add accessor for URN on ActivatedDialWait

- flows/engine/session.go
- flows/runs/run.go
Fixes https://sentry.io/organizations/nyaruka/issues/2277389227/?project=1285856
> Fix resuming a parent run when flow is missing

- cmd/docgen/docs/base_test.go
- excellent/functions/builtin.go
- excellent/functions/builtin_test.go
> 🧮 Add SUM() excellent function

- flows/engine/testdata/templates.json
- flows/triggers/base_test.go
- flows/triggers/testdata/TestTriggerMarshaling_manual.snap
- flows/triggers/testdata/TestTriggerMarshaling_ticket_closed.snap
- flows/triggers/testdata/manual.json
- flows/users.go
- flows/users_test.go
By giving them an always non-empty default and a first_name property
> 🕊️ Make users more like contacts in expressions

- cmd/docgen/docs/base_test.go
- excellent/functions/builtin.go
- excellent/functions/builtin_test.go
- excellent/functions/wrappers.go
User request.. doesn't feel unreasonable
> 🧿 Add unique function to get unique elements in an array

- contactql/es/query.go
- contactql/es/query_test.go
- contactql/evaluator.go
- contactql/evaluator_test.go
- contactql/inspect.go
- contactql/inspect_test.go
- contactql/parser.go
- contactql/parser_test.go
- contactql/visitor.go
- flows/contact_test.go
- flows/group.go
So that during imports we can extract dependencies, ensure they exist and only validate them after everything has been committed
> 🔍 Separate query parsing, validation and evaluation

- contactql/es/query.go
- contactql/es/query_test.go
- contactql/es/testdata/to_query.json
- contactql/evaluator.go
- contactql/parser.go
Use resolver that query was parsed with no there is no possibility of erroring
> 💈 Simplify converting queries to elastic

- assets/references_test.go
- assets/user.go
- flows/actions/add_contact_groups.go
- flows/actions/add_input_labels.go
- flows/actions/base.go
- flows/actions/open_ticket.go
- flows/actions/remove_contact_groups.go
- flows/actions/testdata/_assets.json
- flows/actions/testdata/open_ticket.json
- flows/inspect/templates_test.go
- utils/validator.go
- utils/validator_test.go
In the same way that group and label references can be variable, e.g. `{"name_match": "@fields.district"}`, this lets user references also be, e.g. `{"email_match": "@fields.supervisor_email"}`
> ⚡ Variable user references

- flows/actions/open_ticket.go
- flows/actions/testdata/_assets.json
- flows/actions/testdata/open_ticket.json
- flows/modifiers/base.go
- flows/modifiers/field.go
- flows/modifiers/language.go
- flows/modifiers/name.go
- flows/modifiers/status.go
- flows/modifiers/timezone.go
- flows/modifiers/urn.go
- flows/modifiers/urns.go
> Re-evaluate dynamic groups after opening tickets

- flows/engine/testdata/templates.json
- flows/triggers/base.go
- flows/triggers/base_test.go
- flows/triggers/campaign.go
- flows/triggers/testdata/campaign.json
- flows/triggers/testdata/channel.json
- flows/triggers/testdata/flow_action.json
- flows/triggers/testdata/manual.json
- flows/triggers/testdata/msg.json
- flows/triggers/testdata/ticket.json
Add #1075. Punting on adding the event for now because those don't have a name
> Add `@trigger.campaign` for campaign triggers

- cmd/docgen/docs/base_test.go
- excellent/functions/builtin.go
- excellent/functions/builtin_test.go
- excellent/functions/wrappers.go
```
@(concat(array("a", "b"), array("c", "d"))) -> [a, b, c, d]
@(unique(concat(array(1, 2, 3), array(3, 4)))) -> [1, 2, 3, 4]
```
> Add `concat` excellent function

- contactql/es/query.go
- contactql/es/testdata/to_query.json
- contactql/parser.go
- contactql/parser_test.go
for consistency with other fields
> Allow querying on whether group is set or not 

- flows/actions/send_msg.go
- flows/actions/testdata/_assets.json
- flows/actions/testdata/send_msg.json
If no translation found for contact language. See https://groups.google.com/g/rapidpro-dev/c/-kR1MuvSdng/m/KNaLIlhzAwAJ
> `send_msg` action should fallback to template translation in env default language

- contactql/evaluator.go
- flows/contact_test.go
> Fix not equals conditions in contact queries on fields that aren't set

- flows/actions/base_test.go
- flows/actions/start_session.go
- flows/actions/testdata/start_session.json
- flows/events/base_test.go
- flows/events/session_triggered.go
- test/testdata/runner/all_actions.test.json
Part 1 of https://github.com/rapidpro/rapidpro/issues/1662
> Add option to exclude contacts in a flow on start session action

- flows/engine/session.go
- flows/engine/session_test.go
> Ensure that failing a session doesn't leave runs in active/waiting state

- flows/engine/session_test.go
- flows/routers/waits/msg_test.go
- test/session.go
> Allow passing of a flows.SessionAssets to test.SessionBuilder

- flows/events/dial_wait.go
- flows/routers/waits/dial.go
- flows/routers/waits/dial_test.go
- test/testdata/runner/ivr_dial.busy.json
60 seconds for dialing, 2 hours for the call
> Set defaults for dial wait time limits

- flows/runs/run.go
- flows/runs/run_test.go
- flows/runs/testdata/translation_assets.json
> Remove merging of translation text arrays

- flows/actions/base.go
- flows/actions/play_audio.go
- flows/actions/say_msg.go
- flows/actions/send_email.go
- flows/actions/send_msg.go
- flows/actions/set_run_result.go
- flows/interfaces.go
- flows/routers/base.go
- flows/routers/switch.go
- flows/runs/run.go
> Simplify run text localization methods

- excellent/functions/builtin.go
- excellent/functions/builtin_test.go
- excellent/types/base.go
Fixes https://textit.sentry.io/issues/3960098152/?project=1281372
> Sort should return error (instead of panic) if array has mixed types

- flows/actions/base_test.go
- flows/actions/open_ticket.go
- flows/actions/testdata/open_ticket.json
- flows/contact.go
- flows/contact_test.go
- flows/engine/session_test.go
- flows/engine/testdata/templates.json
- flows/events/base_test.go
- flows/modifiers/testdata/ticket.json
- flows/modifiers/ticket.go
- flows/runs/run.go
- flows/tickets.go
- flows/tickets_test.go
- test/session.go
- test/testdata/runner/ticketing.test.json
For now we still keep `@contact.tickets` around
> Contacts only have one (open) ticket

- envs/language.go
- envs/locale.go
- envs/locale_test.go
Using golang's `languages` module
> Add better locale matching

- flows/actions/send_msg.go
- flows/actions/testdata/send_msg.json
- flows/msg.go
- flows/msg_test.go
Changes as requested in https://github.com/nyaruka/goflow/pull/1199/files#r1422800724
This PR will be merged in the branch for https://github.com/nyaruka/goflow/pull/1199/files
> Replace TemplateParam with ComponentsVariables

- flows/actions/send_msg.go
- flows/actions/testdata/_assets.json
- flows/actions/testdata/send_msg.json
> Support more WA templates components

- flows/actions/send_msg.go
- flows/actions/testdata/_assets.json
- flows/actions/testdata/request_optin.json
- flows/actions/testdata/send_msg.json
- flows/inspect/templates.go
- flows/interfaces.go
- utils/misc.go
* Fix logic for evaluating and localizing component params
* Include template param values in expression enumeration
* Don't include quick replies or attachments on preview messages for now since we don't have their text content to do variable substitution on
> Templating fixes

- flows/runs/summary.go
- test/testdata/runner/expirations.test_all_expire.json
- test/testdata/runner/expirations.test_input_for_all.json
Step 1 of https://github.com/nyaruka/goflow/issues/830
> Mark `@child.run.status` as deprecated in context

- assets/static/template.go
- assets/static/template_test.go
- assets/template.go
Not changing send message bahavior here - leaving that for https://github.com/nyaruka/goflow/pull/1232 - but need type on component to change how mailroom loads them
> Add type and display fields to template components

- flows/actions/send_msg.go
Requires https://github.com/nyaruka/rapidpro/pull/5285
> Remove support for old template component types

- flows/msg.go
- flows/msg_test.go
And return locale rather than language
> Rework broadcast translation selection to merge across text, attachments and quick replies

- assets/static/template.go
- assets/static/template_test.go
- assets/template.go
- flows/actions/send_msg.go
- flows/actions/testdata/send_msg.json
- flows/msg.go
- flows/msg_test.go
- flows/template_test.go
as it's not needed by engine and can be added by mailroom when queueing
> Remove namespace on template translations

- flows/actions/send_msg.go
- flows/template.go
- flows/template_test.go
So it can be re-used by broadcast sending code in mailroom
> Move code to generate templating into `flows.Template`

- flows/definition/flow.go
- flows/definition/flow_test.go
- flows/definition/node.go
- flows/definition/testdata/broken_flows/too_many_actions.json
- flows/definition/testdata/broken_flows/too_many_categories.json
- flows/definition/testdata/broken_flows/too_many_exits.json
- flows/definition/testdata/broken_flows/too_many_nodes.json
- flows/routers/base.go
1000 nodes per flow, 100 actions per node, 100 exits per node, 100 categories per router
> Add limits for nodes per flow, actions per node, categories and exits

- flows/definition/migrations/13_x.go
- flows/definition/migrations/primitives.go
- flows/definition/migrations/testdata/migrations/14.0.0.json
Might as well do some work since we're migrating flows anyway
> Fix invalid expires values in 14.0.0 migration

- flows/actions/open_ticket.go
- test/testdata/runner/ticketing_resultless.json
- test/testdata/runner/ticketing_resultless.test.json
but always write a local that can be used for splitting
> Make result optional on open ticket actions

- flows/call.go
- flows/resumes/dial.go
- flows/resumes/wait_expiration.go
- test/testdata/runner/ivr_dial.busy.json
IVR sessions don't last very long so safe to make these changes now
> Cleanup after recent IVR related changes

- flows/engine/legacy.go
- flows/engine/run.go
- flows/engine/run_test.go
- flows/run.go
- flows/session.go
- test/testdata/runner/all_actions.test.json
- test/testdata/runner/brochure.test.json
- test/testdata/runner/date_parse.test.json
- test/testdata/runner/default_result.test.json
- test/testdata/runner/enter_flow_loop.test.json
- test/testdata/runner/expirations.test_input_for_all.json
- test/testdata/runner/extra.test.json
- test/testdata/runner/initial_wait.test.json
- test/testdata/runner/legacy_favorites.test.json
- test/testdata/runner/legacy_registration.test.json
- test/testdata/runner/legacy_subflow.test.json
- test/testdata/runner/llm_categorize.failure.json
- test/testdata/runner/llm_categorize.flight.json
- test/testdata/runner/nlu_booking.flight.json
- test/testdata/runner/number_quiz.exceed_limit.json
- test/testdata/runner/phone_number.test.json
- test/testdata/runner/subflow.test.json
- test/testdata/runner/subflow_loop_with_wait.test.json
- test/testdata/runner/subflow_other.test.json
- test/testdata/runner/ticketing.test.json
- test/testdata/runner/ticketing_resultless.test.json
- test/testdata/runner/two_questions.test.json
- test/testdata/runner/two_questions_offline.test.json
- test/testdata/runner/webhook_migrated.test.json
- test/testdata/runner/webhook_results.test.json
to replace tracking of `msg_received` events internally, part of #1410
> Add `had_input` field to runs 

- flows/events/base_test.go
- flows/events/chat_started.go
- flows/events/testdata/TestEventMarshaling_chat_started.snap
- flows/triggers/base_test.go
- flows/triggers/chat.go
- flows/triggers/deprecated.go
- flows/triggers/testdata/TestTriggerMarshaling_call_missed.snap
- flows/triggers/testdata/TestTriggerMarshaling_campaign.snap
- flows/triggers/testdata/TestTriggerMarshaling_chat_new_conversation.snap
- flows/triggers/testdata/TestTriggerMarshaling_chat_referral.snap
- flows/triggers/testdata/TestTriggerMarshaling_flow_action.snap
- flows/triggers/testdata/TestTriggerMarshaling_flow_action_batch.snap
- flows/triggers/testdata/TestTriggerMarshaling_manual.snap
- flows/triggers/testdata/TestTriggerMarshaling_manual_minimal.snap
- flows/triggers/testdata/TestTriggerMarshaling_msg.snap
- flows/triggers/testdata/TestTriggerMarshaling_optin_started.snap
- flows/triggers/testdata/TestTriggerMarshaling_optin_stopped.snap
- flows/triggers/testdata/TestTriggerMarshaling_ticket_closed.snap
- flows/triggers/testdata/chat.json
Every we want in chat history has to be _real_ event so this for channel "events" `new_conversation` and `referral`
> Add `chat_started` events and chat triggers

- flows/actions/base_test.go
- flows/actions/open_ticket.go
- flows/actions/testdata/open_ticket.json
- flows/contact.go
- flows/contact_test.go
- flows/engine/run.go
- flows/group.go
- flows/modifiers/testdata/ticket.json
- flows/modifiers/ticket.go
- flows/tickets.go
- test/session.go
which is the way it used to be.. but idea is that we can pack other tickets into that list to be operated on by ticket modifiers
> Replace contact.ticket with list that can hold other tickets

- flows/actions/testdata/send_msg.json
- flows/actions/testdata/transfer_airtime.json
- flows/events/airtime_transferred.go
Part of https://github.com/nyaruka/goflow/issues/1450
> Tweak airtime events to use identity URNs
