cmd/flowserver/flow.go
excellent/functions_test.go
excellent/tests_test.go
flows/actions/save_contact_field.go
flows/actions/update_contact.go
flows/contact.go
flows/definition/localization.go
flows/engine/engine.go
flows/interfaces.go
flows/routers/switch.go
flows/runs/run.go
utils/dates_test.go
utils/environment.go
utils/language.go

Gets rid FlowRun.flowTranslations altogether because we can't pick a single language translation for the run - that translation might not have a specific text, so need to always cascade thru all the language translations.

Update localization to cascade thru contact languages

---

cmd/flowrunner/testdata/flows/all_actions_test.json
cmd/flowrunner/testdata/flows/brochure_test.json
cmd/flowrunner/testdata/flows/date_parse_test.json
cmd/flowrunner/testdata/flows/default_result_test.json
cmd/flowrunner/testdata/flows/empty_test.json
cmd/flowrunner/testdata/flows/node_loop_test.json
cmd/flowrunner/testdata/flows/subflow.json
cmd/flowrunner/testdata/flows/subflow_loop_test.json
cmd/flowrunner/testdata/flows/subflow_other.json
cmd/flowrunner/testdata/flows/subflow_test.json
cmd/flowrunner/testdata/flows/two_questions_test.json
cmd/flowrunner/testdata/flows/webhook_persists.json
cmd/flowrunner/testdata/flows/webhook_persists_test.json
excellent/tests.go
flows/definition/legacy.go
flows/events/flow_exited.go
flows/interfaces.go
utils/http.go

We use self-describing constants everywhere else for things like event types so not seeing a reason to keep these as single chars, e.g. "expired" vs "errored" instead of "E" vs "X"

Self-describing constants for run and webhook statuses

---

cmd/docgen/run.go
cmd/flowrunner/main.go
cmd/flowrunner/runner_test.go
cmd/flowrunner/testdata/channels/default.json
cmd/flowrunner/testdata/flows/all_actions_test.json
cmd/flowrunner/testdata/flows/brochure_test.json
cmd/flowrunner/testdata/flows/date_parse_test.json
cmd/flowrunner/testdata/flows/default_result_test.json
cmd/flowrunner/testdata/flows/empty_test.json
cmd/flowrunner/testdata/flows/node_loop_test.json
cmd/flowrunner/testdata/flows/subflow_loop_test.json
cmd/flowrunner/testdata/flows/subflow_test.json
cmd/flowrunner/testdata/flows/two_questions_test.json
cmd/flowrunner/testdata/flows/webhook_persists_test.json
cmd/flowserver/flow.go
flows/actions/start_flow.go
flows/channel.go
flows/definition/flow.go
flows/engine/engine.go
flows/engine/environment.go
flows/events/flow_exited.go
flows/events/msg_received.go
flows/inputs/base.go
flows/inputs/envelope.go
flows/inputs/msg.go
flows/interfaces.go
flows/runs/context.go
flows/runs/run.go
flows/runs/session.go

This wasn't supposed to turn into a refactor but you know how things go. Currently the engine starts up something like:
1. flows + contacts loaded
2. FlowEnvironment created from the flows + runs + contacts
3. Session created from that
4. Runs created and assigned a session, also added to the FlowEnvironment
But this PR reworks things so that:
1. flows + channels + contacts loaded
2. SessionEnvironment created from the flows + channels + contacts (i.e. dependencies)
3. Session created from that
4. Runs created from the session (i.e. no such thing as a session-less run)
This means things in the session don't have to store UUIDs for flows, contacts and channels, and resolve those later to real objects - they can resolve them as they're being unmarshaled.
Arguably we need to go one step …

Sessions and runs refactor

---

flows/definition/legacy.go
flows/definition/testdata/test_migrations.json
utils/conversions.go

* Migrate templates found in arguments to numeric tests
* Use original string in decimal parsing errors (I was seeing a weird error about not being able to parse `"@c0ntact..."`)

Numeric test fixes

---

flows/definition/legacy.go
flows/definition/testdata/ruleset_migrations.json

I'm not sure if we've every supported this in the real world but we have a unit test which sets up a numeric test with actual numeric values (rather than strings containing numbers). Figure we might as well support it in case there are any legacy flows out there like this.

Allow test values for legacy numeric tests to be read as actual floating point values

---

flows/actions/start_flow.go
flows/engine/flow_stack.go
flows/engine/session.go
flows/interfaces.go
flows/runs/run.go

Currently the logic for avoid flow loops doesn't allow something like flow A calling into flow B twice without a wait because we'll hit the same nodes in B twice. This PR introduces a "flow stack" which tracks triggered flows and visited nodes.

Flow stack for detecting loops

---

excellent/tests.go
flows/definition/legacy.go
flows/definition/testdata/ruleset_migrations.json
flows/definition/testdata/test_migrations.json

To mimic legacy behaviour we have to set the response body as the flow result... cleanest way to do this is with a different test altogether

Migrating legacy webhook rulesets, take II

---

cmd/flowserver/migrate.go
flows/definition/legacy.go

Legacy flows currently reference contact fields by their key but before we try to execute flows in goflow we should ensure that fields exist and have UUIDs

Assume save actions in legacy flows provide field UUIDs

---

utils/conversions.go
utils/resolver.go
utils/validator.go

Fixes https://github.com/nyaruka/goflow/issues/50 which was blowing up because `variable` is a non-nil interface... containing a nil pointer.

Small fixes

---

cmd/docgen/run.go
cmd/flowrunner/runner_test.go
cmd/flowrunner/testdata/flows/all_actions.json
cmd/flowrunner/testdata/flows/all_actions_test.json
cmd/flowrunner/testdata/flows/brochure.json
cmd/flowrunner/testdata/flows/brochure_test.json
cmd/flowrunner/testdata/flows/date_parse_test.json
cmd/flowrunner/testdata/flows/default_result_test.json
cmd/flowrunner/testdata/flows/empty_test.json
cmd/flowrunner/testdata/flows/node_loop_test.json
cmd/flowrunner/testdata/flows/subflow_loop_test.json
cmd/flowrunner/testdata/flows/subflow_other_test.json
cmd/flowrunner/testdata/flows/subflow_test.json
cmd/flowrunner/testdata/flows/two_questions_test.json
cmd/flowrunner/testdata/flows/webhook_persists_test.json
excellent/tests.go
flows/actions/add_to_group.go
flows/actions/base.go
flows/actions/remove_from_group.go
flows/actions/send_msg.go
flows/contact.go
flows/definition/legacy.go
flows/definition/testdata/action_migrations.json
flows/engine/assets.go
flows/events/add_to_group.go
flows/events/remove_from_group.go
flows/group.go
flows/interfaces.go
utils/json.go

**Groups as assets**
Flows can request a single group (`Group`) or the set of all groups (`GroupSet`) as assets. As an optimization, we only ever fetch the set of all groups, and use that to find individual groups.
**Groups in flows**
These are now modelled as `GroupReference`, similar to `ContactReference`. They're either an object with UUID and name, or a name value which is an expression which evaluates to an existing group (see https://github.com/rapidpro/rapidpro/issues/627).
**Groups on contacts**
These are all just UUIDs now, tho they are still loaded as group objects at session read time. This will likely have to change in the future if we want to contacts to be treated as assets sometimes (e.g. the contact of a parent run if it differs from the current contact).
**Groups on …

Group assets and actions

---

excellent/legacy.go
excellent/legacy_test.go
flows/contact.go

Thought about requiring `@(first_word(contact.name))` but seems like this is such a common case that we should make it easy?

Support @contact.first_name

---

cmd/docgen/run.go
cmd/flowrunner/main.go
cmd/flowrunner/runner_test.go
cmd/flowserver/config.go
cmd/flowserver/main.go
cmd/flowserver/server.go
cmd/flowserver/server_test.go
flows/engine/assets.go
flows/engine/assets_test.go
flows/engine/session.go

Addresses #127. Flow server requests now take an asset_server component which configures authentication as well the asset type URLs, e.g.
```json
"asset_server": {
"auth_header": "Token 12345678901234567890",
"type_urls": {
"flow": "http://testserver/assets/flow",
"group": "http://testserver/assets/group"
}
}
```
Have also tried to simplify the cache+server asset stuff and have added a mocked asset server to enable better testing.

Asset server authentication

---

cmd/flowrunner/testdata/flows/all_actions.json
cmd/flowrunner/testdata/flows/all_actions_test.json
cmd/flowrunner/testdata/flows/brochure_test.json
cmd/flowrunner/testdata/flows/date_parse_test.json
cmd/flowrunner/testdata/flows/default_result_test.json
cmd/flowrunner/testdata/flows/dynamic_groups_test.json
cmd/flowrunner/testdata/flows/node_loop_test.json
cmd/flowrunner/testdata/flows/subflow_loop_test.json
cmd/flowrunner/testdata/flows/subflow_other_test.json
cmd/flowrunner/testdata/flows/subflow_test.json
cmd/flowrunner/testdata/flows/triggered_test.json
cmd/flowrunner/testdata/flows/two_questions_test.json
cmd/flowrunner/testdata/flows/webhook_persists_test.json
flows/actions/reply.go
flows/actions/send_email.go
flows/actions/send_msg.go
flows/definition/legacy.go
flows/definition/testdata/migrations/actions.json
flows/events/send_email.go
flows/events/send_msg.go

Changes how `send_email` and `send_msg` actions work so they generate a single event with multiple recipients. This is consistent with `start_session` and makes it easier for the caller to handle these as broadcasts.

Bulk send events

---

flows/definition/legacy_test.go
flows/definition/testdata/migrations/actions.json
flows/runs/run.go

It's possible to have some replies not translated (e.g. `[{"eng": "Yes", "fra": "Oui"}, {"eng": "No"}]`) in which case we need to merge the translated replies we do have with the native ones.

Fix quick replies when language translations are missing

---

cmd/docgen/functions.go
cmd/docgen/run.go
cmd/exptester/main.go
cmd/flowserver/server.go
excellent/evaluator.go
excellent/evaluator_test.go
excellent/functions.go
excellent/functions_test.go
excellent/legacy.go
excellent/legacy_test.go
flows/actions/add_urn.go
flows/actions/base.go
flows/actions/call_webhook.go
flows/actions/save_contact_field.go
flows/actions/save_flow_result.go
flows/actions/send_email.go
flows/actions/update_contact.go
flows/definition/legacy.go
flows/definition/testdata/migrations/actions.json
flows/urns.go
flows/urns_test.go

URN expressions

---

flows/actions/send_email.go
flows/actions/update_contact.go
flows/definition/legacy.go
flows/events/update_contact.go

* Allow blank values in update_contact actions (e.g. clear language)
* Migrate old save action with field=tel_e164 to a new add_urn action
* Remove new lines from email subjects
* Some extra whitespace trimming

Tweaks to match RapidPro

---

excellent/legacy.go
excellent/legacy_test.go

* Properly migrate `@parent.contact.*` and `@child.contact.*`
* Add support for URN subitems, e.g. `@contact.tel.path`

Legacy expression migration fixes

---

cmd/flowrunner/main.go
cmd/flowserver/static/start.json
flows/actions/reply.go
flows/channel.go
flows/contact.go
flows/engine/session_test.go
flows/engine/testdata/trigger.json
flows/urns.go
flows/urns_test.go

Introduces a `ContactURN` as a wrapper for URNs on a contact so we can extract their channel like https://github.com/nyaruka/goflow/compare/new_urns?expand=1#diff-488bb6c851b01295dc4960583fb229d8R38

Add support for URNs with channels as query params

---

cmd/flowserver/main.go
cmd/flowserver/server.go
cmd/flowserver/server_test.go
flows/actions/add_urn.go
flows/definition/legacy.go
flows/engine/assets.go
flows/engine/session.go
flows/runs/run.go

It's super useful to see the actions and events being applied in the engine.
```
DEBU[0011] caller event applied                          code=msg_received data="{\"type\":\"msg_received\",\"created_on\":\"2018-03-12T14:28:04.526231364Z\",\"msg\":{\"uuid\":\"0fcff8f9-d549-4b03-9edc-a43ec1087cd3\",\"urn\":\"tel:+12065550100\",\"channel\":{\"uuid\":\"03123351-3e00-4268-b8d7-89f916e86afc\",\"name\":\"Test Channel\"},\"text\":\"Trey Anastasio\"}}" run=9a1c091d-75f9-467b-b11d-405cbc8cc4cc
```

Log actions and events when debug logging is enabled

---

cmd/flowrunner/testdata/flows/all_actions.json
cmd/flowrunner/testdata/flows/brochure.json
cmd/flowrunner/testdata/flows/default_result.json
cmd/flowrunner/testdata/flows/two_questions.json
docs/index.html
excellent/functions.go
excellent/functions_test.go
flows/actions/set_contact_property.go
legacy/definition.go
legacy/expressions.go
legacy/expressions_test.go
legacy/testdata/migrations/actions.json

1. Rename `field_name` to `property` on `set_contact_property` action (matches `contact_property_changed` event)
2. Fix `word(..)` function being 1-indexed unlike everything else in Excellent2
Fixes #195 
cc @ycleptkellan @ericnewcomer

Rename field_name to property on SetContactProperty action and fix word(..)

---

excellent/evaluator_test.go
excellent/tests.go
flows/attachments.go
flows/channel.go
flows/contact.go
flows/definition/flow.go
flows/fields.go
flows/group.go
flows/inputs/base.go
flows/inputs/msg.go
flows/results.go
flows/runs/context.go
flows/runs/run.go
flows/triggers/base.go
flows/urns.go
legacy/expressions.go
utils/conversions.go
utils/conversions_test.go
utils/http.go
utils/json.go
utils/resolver.go

Playing around with variable resolving. The idea would be:
* All variables in excellent should be one of:
- A primitive of an `XAtom` type
- A complex object that implements `VariableAtomizer`, i.e. can reduce itself to an `XAtom`
- Lists of either of the above (these would cease to be `XAtom` types themselves)
* Make sure the excellent visitor can only produce such types, and we can greatly simply our conversion functions to not worry about other golang types.
* Replace `Default()` and `String()` with `Atomize()` which does the reduction to a primitive (usually a `string`). For example datetime field value returns itself as a `time.Time` - it doesn't need to know how to stringify itself - the conversion routines in utils have that logic in one place.
In this PR I've left `String()` …

Resolving refactor part 1

---

excellent/evaluator_test.go
excellent/functions/functions.go
excellent/functions/functions_test.go
excellent/types/array.go
excellent/types/base.go
excellent/types/bool.go
excellent/types/conversions.go
excellent/types/conversions_test.go
excellent/types/date.go
excellent/types/error.go
excellent/types/json.go
excellent/types/map.go
excellent/types/number.go
excellent/types/string.go
excellent/visitor.go
flows/fields.go
flows/routers/tests/tests.go

So that test output is like `types.XDate{2017-12-01T00:00:00.000000Z}` instead of `types.XDate{wall:0x0, ext:63647683200, loc:(*time.Location)(nil)}`
This PR introduces a base struct to X primitives so they need to become structs instead of type aliases. That means you have to be explicit about calling `.Native()` to get the underlying native value, but I think I prefer that over it sometimes working without that.

Make XTypes Stringify (%s) same as their XString

---

cmd/flowrunner/testdata/flows/webhook_persists.json
docs/docs.md
docs/index.html
flows/routers/tests/tests.go
flows/webhook.go
legacy/definition.go
legacy/testdata/migrations/rulesets.json
legacy/testdata/migrations/tests.json

Introduces `has_webhook_status` test which produces results like:
```json
"response_1": {
"category": "Success",
"node_uuid": "87000b5e-7cdb-4e6f-8d85-4c34c2a6f6c5",
"name": "Response 1",
"value": "{ \"text\": \"Get\", \"blank\": \"\" }",
"created_on": "2018-04-24T14:52:16.33261135Z",
"input": "GET http://localhost:49999/check_order.php?phone=%2B250788383383"
}
```
Note that in legacy engine input is blank - but having something here seems preferable and means we don't have to treat webhooks as a special case - result input is always the test operand stringified. Could update legacy webhooks to match this behaviour.
Fixes #270

Webhook test

---

legacy/definition.go
legacy/definition_test.go
legacy/testdata/flows.json
legacy/testdata/tests.json
legacy/utils.go
legacy/utils_test.go

Can unmarshal translatable items from a single string

Handle legacy flows with missing translations

---

cmd/flowrunner/runner_test.go
cmd/flowrunner/testdata/flows/router_tests.json
cmd/flowrunner/testdata/flows/router_tests_test.json
flows/engine/session.go
legacy/expressions/context.go
legacy/expressions/migrate_test.go
legacy/testdata/actions.json
legacy/testdata/rulesets.json

* Taking the default exit of a router should still save a result as long as the router has a name
* Migrate `@contact.<scheme>` expressions to `@(format_urn(contact.urns.<scheme>))` instead of `@(format_urn(contact.urns.<scheme>.0))` as the former won't error if there's no such URN
Would fix trial failures like https://sentry.io/nyaruka/rapidpro/issues/542067797/?query=is:unresolved

Router result and legacy URN expression migration fixes

---

legacy/definition.go
legacy/testdata/rulesets.json

You can create an explicit Other category (e.g. to match "other" as a keyword) and it doesn't merge with the implicit Other category. So when we migrate, these need to kept as distinct exits.

Migrate rulesets where there is an explicit Other category

---

cmd/flowrunner/testdata/flows/all_actions.json
cmd/flowrunner/testdata/flows/all_actions_test.json
excellent/evaluator.go
utils/text.go
utils/text_test.go

We've been using `url.QueryEncode` which uses `+` for spaces but the problem is that we don't know that the expression is going to be in the query part of the URL

🌐 Encode spaces as %20 in URL expressions

---

flows/assets/cache.go
flows/assets/server.go
flows/assets/session.go
flows/interfaces.go
flows/location.go
flows/runs/environment.go
test/session.go

So that we're consistent with asset server URLs - `/foo/` returns a set and `/foo/xyz` returns an object

LocationHierarchy assets should be managed like a set like other asset types

---

cmd/flowserver/handlers.go
legacy/definition.go
legacy/definition_test.go

Simplifies legacy flow migration by doing one flow at a time - this is how we always use it now from RapidPro

Migrate flows individually

---

flows/assets/assets_test.go
flows/assets/cache.go
flows/assets/server.go

Equivalent RapidPro change: https://github.com/nyaruka/rapidpro/pull/2054

🍫 Wrap multiple asset responses in a results object

---

cmd/flowrunner/main.go
cmd/flowrunner/runner_test.go
cmd/flowserver/handlers.go
cmd/flowserver/server_test.go
flows/definition/flow_test.go
flows/engine/session.go
test/session.go

Since we don't actually need an Asset server, just something that can return the appropriate objects for us.

pass flows.SessionAsset instead of AssertServer to NewSession and ReadSession

---

docs/expressions.html
docs/md/expressions.md
excellent/functions/functions.go
excellent/functions/functions_test.go
flows/routers/tests/tests.go
flows/routers/tests/tests_test.go
legacy/expressions/functions.go
legacy/expressions/migrate.go
legacy/expressions/migrate_test.go
legacy/expressions/visitor.go
legacy/testdata/tests.json

* Add missing `regex_match` func and migrate to that from `regex_group` calls in legacy flows
* Fix migration of string literals in legacy flows so regular expressions aren't escaped
Fixes #370

🚆 Regex fixes

---

cmd/flowrunner/main.go
docs/expressions.html
docs/functions.json
docs/md/expressions.md
excellent/functions/functions.go
excellent/functions/functions_test.go
flows/contact_test.go
flows/routers/tests/tests.go
flows/routers/tests/tests_test.go
legacy/expressions/migrate_test.go
utils/dates_test.go
utils/environment.go

Adds support for parsing/formatting numbers with configurable decimal symbols and thousands separator symbols. Defaults to current RapidPro expectations of `1,234.56`

🔢 Number formats

---

flows/actions/call_resthook.go
flows/actions/call_webhook.go
flows/events/webhook_called.go
flows/webhook.go
flows/webhook_test.go

📪 Use new status of subscriber_gone when resthook call returns 410

---

cmd/docgen/renderers.go
cmd/exptester/main.go
cmd/flowserver/handlers.go
docs/expressions.html
docs/functions.json
docs/md/expressions.md
excellent/evaluator.go
excellent/evaluator_test.go
excellent/functions/functions.go
excellent/functions/functions_test.go
flows/actions/add_contact_urn.go
flows/actions/base.go
flows/actions/call_resthook.go
flows/actions/call_webhook.go
flows/actions/send_email.go
flows/actions/set_run_result.go
flows/engine/session_test.go
flows/interfaces.go
flows/routers/tests/tests_test.go
flows/runs/legacy_test.go
flows/runs/run.go
legacy/definition.go
legacy/expressions/migrate.go
legacy/expressions/migrate_test.go
legacy/testdata/actions.json
test/testdata/flows/all_actions.json
test/testdata/flows/all_actions_test.json
utils/text.go
utils/text_test.go

Unlike webhook URLs, these aren't url encoded in the old engine, and the problem arises when an expression is used for the entire attachment URL and not just a query param.

🌐 Don't url encode msg attachment expressions automatically

---

flows/engine/session.go
flows/engine/session_test.go
flows/interfaces.go
flows/waits/base.go
flows/waits/msg.go

* Waits should check if node still has timeout when they receive a timeout resume
* A wait refusing to end should log an error but no error the session

⏰ Failing waits

---

flows/routers/tests/tests.go
flows/routers/tests/tests_test.go

As discussed at https://github.com/rapidpro/rapidpro/issues/828

🧮 Don't do I>1 O>0 substitutions when parsing numbers

---

flows/urn.go
flows/urn_test.go

Need to use the utility methods in goflow for finding the right channel for a URN and this simplifies the signature so I can do so just with ChannelAssets instead of the whole pile of SessionAssets which is more expensive to build.

simplify signature for ParseRawURN to only need channels assets

---

flows/engine/session.go
flows/engine/sprint.go

Surveyor need a way of creating a sprint from events and modifiers, this just adds a constructor for that so I don't need to create my own Sprint class.

add full constructor for sprint

---

flows/actions/modifiers/base.go
flows/actions/modifiers/base_test.go
flows/actions/modifiers/channel.go
flows/actions/modifiers/field.go
flows/actions/modifiers/groups.go
flows/actions/modifiers/language.go
flows/actions/modifiers/name.go
flows/actions/modifiers/timezone.go
flows/actions/modifiers/urn.go

Addresses #475. So now `ReadModifier` returns...
* a modifier and `nil` error if all assets exist
* a "partial" modifier and `nil` error if some assets exist (e.g. we still have some groups in a groups:add modifier) - with missing group assets reported via the callback
* a nil modifier and nil error if no assets exist and there is no partial modifier to return (with all missing assets reported via the callback)
The last one is the one I'm not sure about.. but I think it's consistent with saying "missing assets isn't actually an error case"

🛂 Update modifier loading so missing assets are reported

---

docs/expressions.html
docs/functions.json
docs/md/expressions.md
excellent/functions/functions.go
excellent/functions/functions_test.go

e.g. `contact.fields.gender` resolves to a `FieldValue` object which has no intrinsic length - so it needs to be first reduced to a primitive (it's `.value`)

🧯 Fix calling length on a complex object that needs to be reduced to a primitive

---

flows/definition/flow.go
flows/definition/flow_test.go
flows/definition/results_info.go
flows/definition/results_info_test.go
test/testdata/flows/brochure.json
test/testdata/flows/brochure_test.json

Upgrades the list of result names returned from flow validation to... a dict of result keys to the result names that map to that key.
I took quick look at the UReport code to see what it needs and whether if this sort of thing was included on the flows.json API endpoint it would be sufficient - but it's using things like rule UUIDs... so I'm thinking UReport might need to continue fetching flow definitions.
@norkans7 @nicpottier

🗺️ Store a map of result keys to result names in a validated flow definition

---

flows/definition/flow.go
flows/definition/flow_test.go
flows/definition/testdata/flow_with_missing_asset.json
test/assets.go
test/testdata/flows/brochure.json

In RP we call `Flow.update` when we import a flow definition... so that happens a lot currently in our unit tests. That method should call `/mr/flow/validate` to validate the flow and get back dependencies and result names... but that can't work from tests because mailroom can't read the assets from the database cuz they only exist in the unit test transaction.
Am thinking we make it so `org_id` is optional on the mailroom /mr/flow/validate endpoint so `Flow.update` can validate a flow in a unit test... the only difference being we won't have validated that it's asset dependencies actually exist.
This seems preferable to always mocking the calls to `/mr/flow/validate` because we'll still get the correct dependencies and result names. We can test the specific case of an asset dependency …

🤷 Allow flow validation without assets

---

flows/definition/results_info.go
flows/definition/results_info_test.go

Want to make it so caller doesn't need to know how to slug keys and then figure out which result names are actually unique results.

🗜️ Merge result infos by key so caller doesn't have to know how to do that

---

flows/routers/tests/tests.go
flows/routers/tests/tests_test.go

We don't do this on the old `RegexTest` and turns out some users rely on this

✋ Don't trim whitespace on input to has_pattern test

---

docs/expressions.html
docs/functions.json
docs/md/expressions.md
excellent/evaluator.go
excellent/evaluator_test.go
excellent/functions/builtin.go
excellent/functions/builtin_test.go
excellent/types/array.go
excellent/types/array_test.go
excellent/types/base.go
excellent/types/dict.go
excellent/types/dict_test.go
excellent/types/text.go
flows/engine/session_test.go
flows/routers/cases/tests.go
flows/runs/legacy.go
legacy/expressions/functions.go
legacy/expressions/functions_test.go

This still feels like a step backwards in terms of simplicity but here we are. Especially since we tried to make `text(x) == x` work as a general principle and it didn't really work. 
`length(urns) == 12343` and `length(dict()) == 2` would be pretty unintuitive so for now am calling the length-converted-to-text method `text_length` (we already have `text_compare`), and the one that works on arrays and dicts, `count`.
We can have a final discussion about function names in a different issue, but I think it's important to make those decisions looking at all the names together.
Addresses #575

Split length() into count() and text_length()

---

flows/actions/add_contact_urn.go
flows/actions/base.go
flows/actions/call_webhook.go
flows/actions/play_audio.go
flows/actions/say_msg.go
flows/actions/send_broadcast.go
flows/actions/send_email.go
flows/actions/send_msg.go
flows/actions/set_contact_field.go
flows/actions/set_contact_language.go
flows/actions/set_contact_name.go
flows/actions/set_contact_timezone.go
flows/actions/set_run_result.go
flows/actions/start_session.go
flows/definition/flow.go
flows/definition/node.go
flows/expressions.go
flows/inspect.go
flows/routers/base.go
flows/routers/switch.go

Addresses #548 by adding a `TemplateIncluder` that can both enumerate and rewrite Excellent templates so those don't have to be separate things.

🧹 Simpler template enumeration and rewriting

---

flows/routers/cases/tests.go
flows/routers/cases/tests_test.go

🧮 Match number like .5 and 1OO (o's) as 1)

---

flows/actions/testdata/_assets.json
flows/actions/testdata/send_msg.json
flows/msg.go

Lua is bananas and considers arrays and dictionaries the same when encoding to JSON. Sadly when it sees something empty it turns it into `{}` instead of `[]` which obviously munges our decoding on the Courier side. Work around by omitting empty variables instead.
This is a hot fix.

🔥 omit empty variables in templates

---

legacy/utils.go
legacy/utils_test.go

Fixes: #667
Customer reported issue. All new attachments aren't being honored since we shipped updated endpoints in RP.

 🔥 Make URLJoin honor absolute urls

---

README.md
cmd/flowrunner/main.go
flows/actions/base_test.go
flows/engine/engine.go
flows/engine/session.go
flows/engine/session_test.go
flows/interfaces.go
flows/routers/base_test.go
flows/routers/waits/msg_test.go
flows/runs/run_test.go
mobile/bindings.go
mobile/bindings_test.go
test/runner_test.go
test/session.go

I've never liked how sessions exist in a weird state between being created and being started. They have a different environment, they could be serialized but not unserialized.. so this PR changes `NewSession` to do the creating and the starting.

💡 Don't create unstarted sessions

---

cmd/flowrunner/main.go
flows/actions/base_test.go
flows/definition/flow.go
flows/definition/flow_test.go
flows/interfaces.go

Have identified the following interactions between mailroom and goflow, and some need to validate a definition without caring about other definitions
* save old flow: 
- no asset validation
- inspect
* save new flow: 
- hard-validate assets, non-recursive
- inspect
* import new flow step 1:
- no asset validation
- inspect
* import new flow step 2:
- clone
- hard-validate assets, non-recursive
* run flow: 
- soft-validate assets, recursive

🤷 Make recursion optional (again) during flow validation

---

cmd/flowmigrate/main.go
cmd/flowmigrate/main_test.go
legacy/compat.go
legacy/definition.go
legacy/definition_test.go
legacy/testdata/flows.json
test/uuid_test.go

There are flows out there which we can't migrate cuz they have rule or actionset destinations which aren't valid

🚀 Ignore invalid destinations when migrating legacy flows

---

legacy/definition.go
legacy/testdata/actions.json

Defaults to `image` as our media type when incoming flow has none set. Items with no `@` are attempted to be turned absolute.

🖼  handle no media type in our migration

---

flows/routers/cases/tests.go
flows/routers/cases/tests_test.go
go.mod
go.sum

We go back and forth on this but in the case of this test I think the right thing is to be aggressive in our search for a phone number but strict in what we find is a valid phone number. This matches our old RapidPro behavior BTW.

☎️  check that numbers are actually valid in our has phone test

---

flows/actions/call_webhook.go
go.mod
go.sum

Currently only allow `[\w\-]+` which is too strict. According to https://godoc.org/golang.org/x/net/http/httpguts#ValidHeaderFieldName it's...
```
RFC 7230 says:
header-field   = field-name ":" OWS field-value OWS
field-name     = token
token          = 1*tchar
tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." /
"^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
```

🤯 Use std lib function to check HTTP headers

---

flows/runs/run.go

When a translation for an item exists,  but has less strings than original
https://sentry.io/organizations/nyaruka/issues/1087555720/?project=227973&referrer=alert_email

🔥 Fix index out of bounds panic during localization

---

contactql/visitor.go

Not being set right now which means nothing is ever redacted.

Set redaction policy in visitor constructor

---

assets/static/types/field.go

Engine doesn't use this - we only added it so that mailroom could use it for it's tracking of field assets
And it being required, means that surveyor can't load previously saved assets that have fields without UUIDs 🤦‍♂

🛏️ Relax requirement for field assets to have UUID

---

flows/actions/call_webhook.go
flows/actions/testdata/call_webhook.json

Have been working on a bigger change to call_webhook that would mean it always saves a result and also need to think of a good solution to https://github.com/nyaruka/goflow/issues/814#issuecomment-567691761
But for now I think with the editor dropping URL validation it's important that goflow gracefully handles things which evaluate to invalid URLs

Perform URL validation in call_webhook and skip action appropriately

---

excellent/tools/context_walk.go
excellent/tools/context_walk_test.go
excellent/types/object.go
excellent/types/object_test.go
flows/engine/session.go
flows/interfaces.go

* Add support for marshaling XObjects with their defaults
* Add tool for walking the context to find objects
So that in mailroom we can do...
```go
context := session.CurrentContext()
tools.ContextFindObjects(context, func(o *types.XObject) {
o.SetMarshalDefault(true)
})
```
and get a version of the context where objects defaults are included in JSON as `__default__`

🧰 Session Current Context Tweaks

---

assets/static/types/global.go
flows/definition/legacy/testdata/actions.json

They already exist apparently, e.g. https://sentry.io/organizations/nyaruka/issues/1473043636/?project=1281372&referrer=alert_email

🧯 Allow globals with empty values

---

contactql/parser.go
contactql/parser_test.go
contactql/visitor.go
flows/contact.go
flows/contact_test.go

* Add `group` as an attribute meaning "any group"
* Fix != with multiple values (e.g. multiple URNs or groups)
* Fix `id` conditions being allowed with `>` `>=` `<` `<=`

🔍 Group conditions and fixes in contact queries

---

contactql/evaluator_test.go
contactql/mock.go
contactql/parser.go
contactql/parser_test.go
contactql/visitor.go
flows/actions/modifiers/base.go
flows/contact.go
flows/contact_test.go
flows/engine/assets.go
flows/field.go
flows/group.go
flows/interfaces.go
flows/triggers/base.go

* Validate that groups exist 
* Validate that language codes are valid
* Disallow `= ""` except for name, language, fields and urns

👮 Stricter contact query parsing

---

README.md
cmd/flowrunner/main.go
cmd/transferairtime/main.go
flows/actions/modifiers/base_test.go
flows/contact.go
flows/contact_test.go
flows/definition/flow_test.go
flows/definition/migrations/base_test.go
flows/engine/assets.go
flows/engine/assets_test.go
flows/engine/session_test.go
flows/field.go
flows/group.go
flows/group_test.go
flows/inputs/base_test.go
flows/inspect/dependencies_test.go
flows/inspect/issues/base_test.go
flows/resumes/base_test.go
flows/runs/summary_test.go
flows/triggers/base_test.go
flows/urn_test.go
mobile/bindings.go
mobile/bindings_test.go
test/assets.go
test/runner_test.go
test/session.go

Pre-requisite for #880. Currently we lazy parse and cache contact queries, but parsing a contact query requires an environment, so we end up using the run-environment of the first contact this gets called for... which might be a different country to subsequent contacts which also use the same session assets.
This PR reworks things so when we're loading assets, we parse group queries, and determine which groups are "broken".

⚙️ Rework group asset loading so that parsing is not deferred

---

cmd/flowrunner/main.go
cmd/flowrunner/main_test.go
flows/actions/testdata/send_broadcast.json
flows/actions/testdata/start_session.json
flows/runs/environment.go
flows/runs/environment_test.go
test/testdata/runner/phone_number.json
test/testdata/runner/phone_number.test.json

Addresses https://github.com/rapidpro/rapidpro/issues/1166
Things like excellent functions (`has_phone`) only have access to an `Environment`.. and know nothing about runs and sessions. Inside a run, when we have templates to evaluate, we create a special `RunEnvironment` which overrides things like timezone and language based on values on the current session contact.

🗺️ Override env country if contact has preferred channel with country

---

i18n/flows.go
i18n/po_test.go
i18n/testdata/translation_mismatches.noargs.es.po

When translations differ, still merge the extractions with the majority translation. For example in the covid bot flow there are two places _MENU_ is translated to _Menu_, one where it's translated to _Other_. _Menu_ wins and we create a context-less entry for that, and a context-specific one for _Other_. I.e. this..
becomes..

🗜️ Merge PO entries with the majority translation

---

docs/expressions.html
docs/functions.json
docs/md/expressions.md
docs/md/routing.md
docs/routing.html
excellent/evaluator_test.go
excellent/functions/builtin.go
excellent/functions/builtin_test.go
excellent/types/base.go
excellent/types/base_test.go
flows/results_test.go
flows/routers/cases/tests.go

Also..
* Simplify implementation of `default` to use the default if ..
- arg1 an error or 
- arg1 stringifies as empty
* Makes `has_value` an alias for `has_text` - we already [removed this](https://github.com/nyaruka/floweditor/issues/725) in the editor and we can do a migration to get rid of it completely at some point.

🦃 Fix default to understand objects with defaults

---

flows/events/base_test.go
flows/info_test.go
flows/services_test.go
services/airtime/dtone/client_test.go
services/airtime/dtone/service_test.go
services/classification/bothub/client_test.go
services/classification/bothub/service_test.go
services/classification/luis/client_test.go
services/classification/luis/service.go
services/classification/luis/service_test.go
services/classification/wit/client_test.go
services/classification/wit/service_test.go
utils/httpx/access_test.go
utils/httpx/http_test.go
utils/httpx/mock_test.go
utils/httpx/retries_test.go

Not sure when go starting allowing this but vscode offers to fix it and seems it works on 1.13 and 1.14..

🧹 Remove redundant types on slice items

---

flows/actions/base.go
flows/actions/testdata/send_broadcast.json

Only treat a legacy var as a contact UUID if it contains exactly a UUID

🔧 Fix evaluation of legacy vars in other-contacts actions

---

flows/actions/add_contact_urn.go
flows/actions/modifiers/base_test.go
flows/actions/modifiers/testdata/urns.json
flows/actions/modifiers/urn.go
flows/actions/modifiers/urns.go
flows/contact.go
flows/contact_test.go

From the RP UI you can completely change/reorder the contact URNs, which currently we'd have to describe using a sequence of single URN add/remove modifiers. This adds a new "URNs" modifier which can eventually replace the "URN" modifier.

📇 URNs modifier to replace/set all URNs

---

README.md
cmd/flowrunner/main.go
cmd/transferairtime/main.go
flows/actions/base_test.go
flows/contact_test.go
flows/resumes/base_test.go
flows/routers/base_test.go
flows/routers/waits/msg_test.go
flows/runs/environment_test.go
flows/triggers/base.go
flows/triggers/base_test.go
flows/triggers/campaign.go
flows/triggers/channel.go
flows/triggers/flow_action.go
flows/triggers/manual.go
flows/triggers/msg.go
mobile/bindings.go
test/session.go

Trying to think of a way to not make our convoluted trigger constructors more convoluted by adding even more arguments, e.g. https://github.com/nyaruka/goflow/issues/929 and whilst still keeping triggers immutable.
The complication here is that there are different types of triggers with different params..
```go
t := triggers.NewBuilder(env, flow.Reference(), contact).  <-- required opts for all triggers here
Msg(msg).                                              <-- type and required opts for that type
WithMatch(keyword).                                    <-- optional opts
Build()
```

🏗️ Add builder for triggers

---

flows/modifiers/groups.go
flows/modifiers/testdata/groups.json

Turns out this is not critical because after after modifier we check if they should be pulled out of groups, but seems we should generate an error event rather than putting them in a group and then removing them.

🛑 No groups for blocked or stopped contacts

---

contactql/error.go
contactql/parser.go
contactql/parser_test.go
utils/errors.go

See https://github.com/rapidpro/rapidpro/issues/1289. Currently if a mailroom web handler returns an error it's returned as JSON as
```json
{
"error": "oops something went wrong"
}
```
But we could make it so that if it sees the error implements `utils.RichError`, then it can render it like..
```json
{
"error": "oops something went wrong",
"code": "missing_foo",
"extra": {"bar": "yes"}
}
```
So in the case of a users searching for $ the mailroom response would look like
```json
{
"error": "mismatched input '$' expecting {'(', TEXT, STRING}",
"code": "query_unexpected_token",
"extra": {"token": "$"}
}
```
And RP can send that back to the user like `_("Invalid search syntax at %(token)s") % token`.. and you could use this for other types of errors, missing fields, un-parseable dates etc.

🧪 ContactQL parser errors should contain more info

---

contactql/error.go
contactql/error_test.go
contactql/es/es.go
contactql/es/es_test.go
contactql/es/testdata/to_query.json
contactql/evaluator.go
contactql/evaluator_test.go
contactql/inspect_test.go
contactql/parser.go
contactql/parser_test.go
contactql/visitor.go
flows/contact.go
flows/contact_test.go
flows/group.go

* Catch more errors at parse time, so that mailroom's parse_query returns errors for things like unparseable dates. Also means that the contactql and engine based evaluators have less separate error handling
* Error codes for all common error cases

⚠️ Rework error handling in contactql 

---

contactql/es/es.go
contactql/es/testdata/to_query.json

See #950. Tested locally and works fine. AFAIK this is the last little subtle difference between the engine and elastic search implementations.

📇 Allow URN inequality in elastic searches

---

flows/actions/base_test.go
services/email/smtp/service.go
services/email/smtp/service_test.go
test/runner_test.go
utils/smtpx/client.go
utils/smtpx/client_test.go
utils/smtpx/mock.go
utils/smtpx/mock_test.go
utils/smtpx/smtp.go

Reworks the `utils/smtpx` package into something more like `httpx` so it could be used by mailroom for emails outside of flows, and addresses https://github.com/nyaruka/goflow/issues/955

📧 Better support for non-flow emailing

---

excellent/types/number.go
excellent/types/number_test.go

Excellent doesn't support number literals written in scientific notation so I think we should be consistent when doing runtime parsing of numbers. I also don't think scientific notation is something we need to support and when parsing does occur its  accidental like when a string happens to look like `1E3153` etc... which then also leads to problems with very big numbers e.g. https://github.com/nyaruka/goflow/issues/963

🧮 Don't parse numbers in scientific notation

---

flows/actions/add_contact_urn.go
flows/actions/set_contact_channel.go
flows/actions/testdata/add_contact_urn.json
flows/modifiers/channel.go
flows/modifiers/testdata/_assets.json
flows/modifiers/testdata/channel.json
flows/modifiers/testdata/urns.json
flows/modifiers/urns.go

Pushes error checking down from the action to the modifier so that when we use modifiers without actions in mailroom, we still get error events

URN and channel modifiers should error with invalid URNs and channels

---

excellent/operators/builtin.go
excellent/operators/builtin_test.go

🧮 Add workaround for exponent expressions with non-integer exponents

---

flows/actions/base.go
flows/actions/testdata/send_msg.json

Does #1000 and stops us from blowing up when mailroom tries to save the message

📏 Log error event and skip when attachment is longer than 2048 limit

---

flows/runs/run.go

I thought [this couldn't happen](https://sentry.io/organizations/nyaruka/issues/2236308663/?project=1285856&referrer=alert_email) - if we're resuming and we can't find the node because the flow has changed from under us, then we error.. but in the case of simulation, we try to resume, _and_ we try to create a map of everything in the context to use in the context explorer. That still needs to work even if we can't find the current node.

🦤 Don't blow up building context if node is null

---

flows/contact.go
flows/contact_test.go
flows/events/base_test.go
flows/tickets.go
flows/tickets_test.go
test/engine.go

* Remove externalID as arg to `flows.NewTicket` since it's never used that way
* Add way to create new ticket reference instances
* Add contact tickets to editor autocompletion

Ticket tweaks

---

flows/actions/open_ticket.go
flows/contact.go
flows/contact_test.go
flows/events/base_test.go
flows/events/ticket_opened.go
flows/tickets.go
flows/tickets_test.go
flows/triggers/base_test.go
flows/triggers/testdata/TestTriggerMarshaling_ticket_closed.snap
flows/triggers/testdata/ticket.json
flows/triggers/ticket.go
test/engine.go

They were a workaround to have a ticket-like struct that marshals/unmarshals

Get rid of ticket references

---

envs/environment.go
envs/environment_test.go
excellent/types/date_test.go
excellent/types/datetime_test.go
flows/actions/base_test.go
flows/contact_test.go
flows/events/base_test.go
flows/events/environment_refreshed.go
flows/runs/environment_test.go
flows/runs/run_test.go
mobile/bindings.go
mobile/bindings_test.go
test/session.go
test/testdata/runner/airtime.test_successful_transfer.json
test/testdata/runner/all_actions.test.json
test/testdata/runner/brochure.test.json
test/testdata/runner/date_parse.test.json
test/testdata/runner/legacy_favorites.test.json
test/testdata/runner/legacy_timeout.test.json
test/testdata/runner/legacy_webhook.test.json
test/testdata/runner/node_loop.test.json
test/testdata/runner/redact_urns.test.json
test/testdata/runner/router_tests.test.json
test/testdata/runner/subflow.test.json
test/testdata/runner/subflow.test_resume_with_expiration.json
test/testdata/runner/subflow_other.test.json
test/testdata/runner/triggered.test.json
test/testdata/runner/two_questions.test.json
test/testdata/runner/two_questions.test_resume_with_expiration.json

We now expect `allowed_languages` to be ordered (at least the first item) and that's what we use as the default. Having to repeat `default_language` in `allowed_languages` always felt a bit redundant and enables a weird state of what does it mean if your `default_language` is not an `allowed_language`..

🌐 Remove default_language from environments 

---

excellent/functions/builtin.go
excellent/functions/builtin_test.go
excellent/functions/utils.go
excellent/functions/utils_test.go

when input contains non-ASCII and tweak contract to be that the result is starts with the second valid word

🔪 Fix `remove_first_word`

---

flows/actions/base.go
flows/events/webhook_called.go
flows/services.go
services/webhooks/service.go
services/webhooks/service_test.go
test/http.go

`json.Valid` seems to only check structure even tho JSON "must" be valid UTF8 according to the [RFC](https://datatracker.ietf.org/doc/html/rfc8259#section-8.1)
https://play.golang.org/p/pXRiYg5sEPZ 
Had my suspicions that webhook responses were one place that invalid UTF-8 can get into the session state and sure enough it looks like https://sentry.io/organizations/nyaruka/issues/2483695525/events/5374e6c59d1d44f49fcc337469302de0/?project=1281372 is caused by a webhook result that includes `"id_number":"01\u00006\u00002"`.. NULL chars.
Initially was thinking we should reject invalid UTF-8 but seem like we can afford to be a bit more forgiving and strip out the invalid UTF-8.

👮 Strip invalid UTF-8 from webhook responses

---

flows/triggers/base_test.go
flows/triggers/msg.go
flows/triggers/testdata/TestTriggerMarshaling_msg.snap

Messages can trigger IVR flows but IVR flows can be run without a connection. 
Usually this isn't a problem because if a message triggers an IVR flow, that becomes a flow start which eventually is started in the engine with a manual trigger. We forget that it came from a message.
But in the simulator, if a message matches a keyword trigger and we want to simulate switching to that flow, we use a Msg type trigger... but we don't set connection.. so if that flow is IVR, we blow up, e.g. https://sentry.io/organizations/nyaruka/issues/2506463195/?project=1281372

🔌 Allow `msg` type triggers to have connections

---

contactql/es/query_test.go
contactql/evaluator.go
contactql/evaluator_test.go
contactql/inspect.go
contactql/inspect_test.go
contactql/parser.go
contactql/parser_test.go
flows/contact.go
flows/contact_test.go
flows/engine/session.go
flows/group.go
flows/modifiers/base.go

* Queries can be parsed with or without a resolver
* Only queries parsed with a resolver can be evaluated
* Inspection optionally uses resolver

🔎 Simplify parsing contact queries

---

contactql/es/query.go
contactql/es/query_test.go
contactql/es/testdata/to_query.json
contactql/evaluator_test.go
contactql/inspect_test.go
contactql/mock.go
contactql/parser_test.go

Requires https://github.com/nyaruka/rp-indexer/pull/39

Switch from `flow` to `flow_id` and from `groups` to `group_ids` for ES queries

---

contactql/es/query.go
contactql/es/testdata/to_query.json
contactql/inspect.go
contactql/parser.go
contactql/visitor.go

As `history = "Name of flow"`.. tho to be reliable for flow starts we're going to need to make flow names unique or let it work against UUIDs as well as names, i.e. if the text is the format of a UUID, treat is as one.

Support contact queries on flow history

---

utils/attachment.go
utils/attachment_test.go

Gonna use this in mailroom to know if courier has already fetched attachments

Make `utils.Attachment` smarter about parsing raw URLs

---

assets/static/template.go
assets/static/template_test.go
assets/template.go
flows/actions/send_msg.go
flows/actions/testdata/_assets.json
flows/actions/testdata/send_msg.json
flows/msg.go
flows/template.go
flows/template_test.go

Replace `TemplateTranslation.language` and `country` fields with single `locale` field and also don't duplicate locale on `MsgTemplating` since it's now on the message itself

Locale for template assets

---

cmd/docgen/docs/base_test.go
excellent/functions/builtin.go
excellent/functions/builtin_test.go
excellent/operators/builtin.go

Note that this is only for arrays - our approach for text  functions thus far has been to make them distinct, e.g. `text_length`

Add `contains` function

---

assets/optin.go
assets/source.go
assets/static/channel.go
assets/static/channel_test.go
assets/static/optin.go
assets/static/optin_test.go
assets/static/source.go
assets/static/source_test.go
cmd/docgen/docs/base_test.go
flows/engine/assets.go
flows/engine/assets_test.go
flows/engine/testdata/templates.json
flows/interfaces.go
flows/optin.go
flows/optin_test.go
flows/triggers/base.go
flows/triggers/base_test.go
flows/triggers/optin.go
flows/triggers/testdata/_assets.json
flows/triggers/testdata/campaign.json
flows/triggers/testdata/channel.json
flows/triggers/testdata/flow_action.json
flows/triggers/testdata/manual.json
flows/triggers/testdata/msg.json
flows/triggers/testdata/optin.json
flows/triggers/testdata/ticket.json
test/assets.go
test/session.go

So that in a flow triggered by an optin or optout, you can do `@trigger.optin`, `@trigger.optin.name` etc 
And whatever action we add to solicit an optin needs to know about optins.

OptIn assets and triggers

---

assets/static/template.go
assets/static/template_test.go
assets/template.go
flows/actions/send_msg.go
flows/template.go
flows/template_test.go

So that it can work with locales that we get from WhatsApp like `en-US` using a smart matcher and so we don't have to map those on the RP side and then map them back in courier.

Rework template translation finding

---

flows/actions/base.go
flows/actions/testdata/send_msg.json

A couple of times we've seen attachments with trailing newlines etc that then blows up in courier trying to parse the URL

Trim whitespace from evaluated message attachments

---

flows/actions/send_msg.go
flows/actions/testdata/send_msg.json
flows/inspect/templates_test.go

And fix enumerating templates and localizable strings.
The previous format didn't play well with go's typing (uuid had to be a string, but every other property a slice of strings), or our engine struct field tags used to enumerate automatically things that are templates or localizable.

Rework `send_msg.templating` to have a simpler structure in flow definitions

---

excellent/types/object.go
excellent/types/object_test.go
flows/results.go

* Support excluding deprecated object properties from marshaling
* Deprecate undocumented multi-match result fields

Deprecated values updates

---

flows/actions/send_msg.go

I think this is https://textit.sentry.io/issues/5069379664/?alert_rule_id=515582&alert_timestamp=1710500035628&alert_type=email&notification_uuid=5623cbac-2390-48c8-aac0-531a26c4ae8e&project=1285856
Generally we might need to have a think about supporting quick replies that are text + payload since that's a thing that several channel types support... but would require a more complex editing widget.

Truncate quick replies for template preview messages

---

flows/actions/send_msg.go
flows/actions/testdata/send_msg.json
flows/msg.go
flows/msg_test.go

We can have mailroom save this as `msg.templating` and the old format (which it can create) as `msg.metadata.templating`
```
"components": [
{
"type": "body",
"name": "body",
"params": [{type": "text", "value": "Bob"}, {type": "text", "value": "TextIt"}]
},
{
"type": "button/quick-reply",
"name": "button.0",
"params": [{type": "text", "value": "A"}]
},
{
"type": "button/url",
"name": "button.1",
"params": [{type": "text", "value": "B"}]
}
]
```
becomes...
```
"components": [
{
"type": "body",
"name": "body",
"variables": {"1": 0, "2": 1}
},
{
"type": "button/quick-reply",
"name": "button.0",
"variables": {"1": 2}
},
{
"type": "button/url",
"name": "button.1",
"variables": {"1": 3}
}
],
"variables": [
{type": "text", "value": "Bob"},
{type": "text", "value": "TextIt"},
{type": "text", …
```

Rework the format of `MsgTemplating`

---

flows/actions/send_msg.go
flows/actions/testdata/send_msg.json
flows/msg.go
flows/msg_test.go

On reflection it's a lot easier to add these back here than have mailroom generate two formats...

Re-include legacy .params field on components temporarily

---

contactql/parser.go
contactql/parser_test.go

Normalize contactql queries with type prefixes

---

flows/actions/base.go
flows/actions/send_msg.go
flows/msg.go
flows/template.go
flows/template_test.go

Move functionality to generate preview content for template message from `send_msg` action to `TemplateTranslation`

Make template message code usable outside of actions part 1

---

cmd/flowrunner/main_test.go
flows/actions/testdata/TestResthookPayload_resthook_payload.snap
flows/definition/flow.go
flows/definition/flow_test.go
flows/events/base_test.go
flows/events/dial_wait.go
flows/events/msg_wait.go
flows/interfaces.go
flows/routers/waits/base.go
flows/routers/waits/dial.go
test/testdata/runner/brochure.test.json
test/testdata/runner/date_parse.test.json
test/testdata/runner/default_result.test.json
test/testdata/runner/extra.test.json
test/testdata/runner/nlu_booking.flight.json
test/testdata/runner/subflow.test.json
test/testdata/runner/subflow.test_resume_with_expiration.json
test/testdata/runner/subflow_loop_with_wait.test.json
test/testdata/runner/subflow_other.test.json
test/testdata/runner/ticketing.test.json
test/testdata/runner/two_questions.test.json
test/testdata/runner/two_questions.test_resume_with_expiration.json
test/testdata/runner/two_questions_offline.test.json
test/testdata/runner/webhook_migrated.test.json

* Use `time.Duration` internally for flow wait expire value
* Add fallback values for expires after for messaging and voice flow types
* Make expires_on non-nil on waits

Wait expiration changes

---

flows/actions/base.go
flows/events/base_test.go
flows/msg.go
flows/msg_test.go
flows/runs/run_test.go
flows/template.go
flows/template_test.go

Because these are in events.. need to temporarily support loading from single string or struct, but always marshaling to string. Then can switch to always marshaling as struct.
Still need to reduce to actual strings to store in `Msg.quick_replies`...

Convert quick replies into structs

---

excellent/functions/builtin.go
excellent/functions/builtin_test.go
flows/actions/base_test.go
test/engine.go
test/runner_test.go
test/services/llm.go
test/testdata/runner/llm_categorize.flight.json

Initially I wanted this as simple as possible so the function itself was doing some formatting.. but moving that to the expression provides more flexibility
```
@(llm_prompt("categorize", array("Positive", "Negative"))) -> "Categorize..: [Positive, Negative]"
@(llm_prompt("categorize", join(array("Positive", "Negative"), ","))) -> "Categorize..: Positive, Negative"
@(llm_prompt("categorize", json(array("Positive", "Negative")))) -> "Categorize..: ["Positive", "Negative"]"
```

Tweak `llm_prompt` so onus is on the caller to format args

---

flows/engine/session.go
flows/events/base.go
flows/events/campaign_fired.go
flows/events/optin_started.go
flows/events/optin_stopped.go
flows/triggers/msg.go
flows/triggers/optin.go
flows/triggers/testdata/campaign.json
flows/triggers/testdata/msg.json
flows/triggers/testdata/optin.json
test/testdata/runner/all_actions.test.json
test/testdata/runner/expirations.test_all_expire.json
test/testdata/runner/initial_wait.test.json
test/testdata/runner/subflow.test_resume_with_expiration.json
test/testdata/runner/two_questions.test_resume_with_expiration.json

Make a bunch of additions we made a month ago, required now:
* `events.BaseEvent.uuid`
* `events.CampaignFired.point_uuid`
* `events.OptInStarted.channel`
* `events.OptInStopped.channel`
* `engine.Session.contact_uuid`
* `triggers.Msg.event`

Enforce recent session state changes, part 1
